import type { MessageCatalogue } from '../../types';

const messages = { assistant: {
  navigation: 'Assistant', title: 'Interroger votre Alliance', eyebrow: 'Assistant d’Alliance · Réponses autorisées',
  subtitle: 'Posez des questions sur les Événements, votre roster, les guides de l’Alliance et les observations. Les réponses reposent sur des sources que vous pouvez déjà consulter.',
  authorizationHint: 'Les réponses utilisent uniquement les données de l’Alliance que vous êtes autorisé à voir.', tryAsking: 'Essayez de demander', conversation: 'Conversation avec l’Assistant d’Alliance', youAsked: 'Vous avez demandé', possibleEvents: 'Événements possibles', openEvent: 'Ouvrir l’Événement', sourcesHeading: 'Sources utilisées', sourceTime: 'Date de la source : {time}', questionLabel: 'Interroger votre Alliance', questionPlaceholder: 'À quelle heure est Swordland et suis-je dans le roster ?', inputHint: '{count}/{max} caractères · Entrée pour demander · Maj+Entrée pour une nouvelle ligne', asking: 'Vérification des sources…', ask: 'Demander', notRecorded: 'Non renseigné',
  classifications: { operational_fact: 'Fait opérationnel', game_fact: 'Données du jeu', alliance_strategy: 'Stratégie de l’Alliance', observation: 'Observation' },
  sources: { event: 'Événement', roster: 'Roster', alliance_content: 'Guide de l’Alliance', observation: 'Observation', game_fact: 'Données du jeu' },
  prompts: { swordland: 'À quelle heure est Swordland et suis-je dans le roster ?', nextEvent: 'Quel est mon prochain Événement ?', bearGuide: 'Que dit notre guide Bear Hunt ?', observation: 'Qu’avons-nous observé au sujet de notre adversaire ?' },
  answers: {
    help: 'Je peux répondre à partir des Événements, de votre roster, des guides de l’Alliance et des observations autorisées. Je n’utilise pas de connaissances KingShot sans source.',
    unsupported: 'Je peux répondre uniquement à partir des Événements autorisés, de votre roster, des guides de l’Alliance et des observations. Je ne peux effectuer aucune modification ici.',
    unavailable: 'L’Assistant d’Alliance ne peut pas vérifier ses sources pour le moment. Réessayez.', rateLimited: 'Vous posez des questions trop rapidement. Réessayez dans un instant.', validationError: 'Saisissez une question de 2 à {max} caractères.', noUpcomingEvent: 'Je n’ai trouvé aucun Événement à venir que vous êtes autorisé à consulter.', eventSubjectMissing: 'Indiquez l’Événement que vous voulez vérifier.', eventNotFound: 'Je n’ai trouvé aucun Événement à venir autorisé correspondant à « {subject} ».', eventAmbiguous: 'Plusieurs Événements correspondent à « {subject} ». Ouvrez ci-dessous celui que vous voulez.', eventTime: '{event} commence {startsAt}.', eventTimeNotRostered: '{event} commence {startsAt}. Vous n’êtes pas actuellement dans le roster.', notRostered: 'Vous n’êtes pas actuellement dans le roster de {event}.', eventTimeRostered: '{event} commence {startsAt}. Vous êtes dans {roster}. Rôle : {role} ; emplacement : {slot} ; statut : {status}.', rostered: 'Vous êtes dans le roster de {event}, dans {roster}. Rôle : {role} ; emplacement : {slot} ; statut : {status}.', contentSubjectMissing: 'Indiquez l’Événement ou le sujet du guide de l’Alliance à vérifier.', contentNotFound: 'Je n’ai trouvé aucun contenu d’Alliance publié correspondant à « {subject} ».', contentFound: 'Stratégie de l’Alliance — {title} : {excerpt}', observationSubjectMissing: 'Indiquez l’Alliance ou le sujet d’observation à vérifier.', observationNotFound: 'Je n’ai trouvé aucune observation autorisée correspondant à « {subject} ».', observationFound: 'Observation — {title} : {observation}'
  }
} } satisfies MessageCatalogue;
export default messages;
