<?php

declare(strict_types=1);

use App\Contexts\GameWorld\Governance\Http\Controllers\KingdomRoleController;
use App\Contexts\GameWorld\KingdomTransfers\Http\Controllers\TransferCohortController;
use App\Contexts\GameWorld\KingdomTransfers\Http\Controllers\TransferCompletionController;
use App\Contexts\GameWorld\KingdomTransfers\Http\Controllers\TransferParticipantController;
use App\Contexts\GameWorld\KingdomTransfers\Http\Controllers\TransferPlanController;
use App\Contexts\GameWorld\KingdomTransfers\Http\Controllers\TransferPlanningController;
use App\Contexts\GameWorld\KingdomTransfers\Http\Controllers\TransferReadinessController;
use App\Contexts\Intelligence\Diplomacy\Http\Controllers\KingdomAllianceDiplomacyContactController;
use App\Contexts\Intelligence\Diplomacy\Http\Controllers\KingdomAllianceDiplomacyController;
use App\Contexts\Intelligence\Ingestion\Http\Controllers\KingdomIngestionController;
use App\Contexts\Intelligence\Observations\Http\Controllers\KingdomAllianceController;
use App\Contexts\Intelligence\Observations\Http\Controllers\KingdomAllianceObservationController;
use App\Contexts\Intelligence\Roster\Http\Controllers\PlayerSnapshotController;
use App\Contexts\Intelligence\Roster\Http\Controllers\RosterController;
use App\Contexts\Intelligence\Roster\Http\Controllers\RosterCsvController;
use App\Contexts\Intelligence\Sharing\Http\Controllers\KingdomIntelligenceSharingController;
use App\ReadModels\KingdomIntelligence\Http\Controllers\KingdomAllianceIntelligenceController;
use App\ReadModels\KingdomSettings\Http\Controllers\KingdomSettingsController;
use App\ReadModels\Roster\Http\Controllers\PlayerSnapshotHistoryController;
use App\ReadModels\Roster\Http\Controllers\RosterImportReadController;
use App\ReadModels\Roster\Http\Controllers\RosterIntelligenceController;
use App\ReadModels\Roster\Http\Controllers\RosterReadController;
use App\ReadModels\SharedKingdomIntelligence\Http\Controllers\KingdomIntelligenceSharingReadController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'auth.session', 'verified', 'alliance.context'])->group(function (): void {
    Route::get('/alliance/settings/kingdom', [KingdomSettingsController::class, 'index'])->name('alliance.kingdom.edit');
    Route::get('/alliance/settings/kingdom/roles', [KingdomRoleController::class, 'index'])->name('alliance.kingdom.roles.index');
    Route::get('/alliance/roster', [RosterReadController::class, 'index'])->name('alliance.roster.index');
    Route::get('/alliance/roster/manage', [RosterReadController::class, 'manage'])->name('alliance.roster.manage');
    Route::get('/alliance/roster/intelligence', [RosterIntelligenceController::class, 'index'])->name('alliance.roster.intelligence');
    Route::get('/alliance/roster/import', [RosterImportReadController::class, 'index'])->name('alliance.roster.import.index');
    Route::get('/alliance/roster/import/{import}', [RosterImportReadController::class, 'show'])->name('alliance.roster.import.show');
    Route::get('/alliance/roster/export.csv', [RosterCsvController::class, 'export'])->name('alliance.roster.export');
    Route::get('/alliance/roster/{entry}/history', [PlayerSnapshotHistoryController::class, 'show'])->name('alliance.roster.history');
    Route::get('/alliance/kingdom-alliances', [KingdomAllianceController::class, 'index'])->name('alliance.kingdom-alliances.index');
    Route::get('/alliance/kingdom-alliances/manage', [KingdomAllianceController::class, 'manage'])->name('alliance.kingdom-alliances.manage');
    Route::get('/alliance/kingdom-alliances/intelligence', [KingdomAllianceIntelligenceController::class, 'index'])->name('alliance.kingdom-alliances.intelligence');
    Route::get('/alliance/kingdom-alliances/{tracking}/history', [KingdomAllianceObservationController::class, 'show'])->name('alliance.kingdom-alliances.history');
    Route::get('/alliance/kingdom-alliances/{tracking}/diplomacy', [KingdomAllianceDiplomacyController::class, 'show'])->name('alliance.kingdom-alliances.diplomacy.show');
    Route::get('/alliance/kingdom-alliances/{tracking}/diplomacy/contacts', [KingdomAllianceDiplomacyContactController::class, 'show'])->name('alliance.kingdom-alliances.diplomacy.contacts.show');
    Route::get('/alliance/kingdom-ingestion/manage', [KingdomIngestionController::class, 'manage'])->name('alliance.kingdom-ingestion.manage');
    Route::get('/alliance/kingdom-sharing', [KingdomIntelligenceSharingReadController::class, 'index'])->name('alliance.kingdom-sharing.index');
    Route::get('/alliance/kingdom-sharing/manage', [KingdomIntelligenceSharingReadController::class, 'manage'])->name('alliance.kingdom-sharing.manage');
    Route::get('/alliance/transfers', [TransferPlanController::class, 'index'])->name('alliance.transfers.index');
    Route::get('/alliance/transfers/manage', [TransferPlanController::class, 'manage'])->name('alliance.transfers.manage');
    Route::get('/alliance/transfers/readiness', [TransferReadinessController::class, 'index'])->name('alliance.transfers.readiness');
    Route::get('/alliance/transfers/completion', [TransferCompletionController::class, 'index'])->name('alliance.transfers.completion');
    Route::middleware('password.confirm')->group(function (): void {
        Route::post('/alliance/settings/kingdom/roles', [KingdomRoleController::class, 'store'])->name('alliance.kingdom.roles.store');
        Route::delete('/alliance/settings/kingdom/roles/{assignment}', [KingdomRoleController::class, 'destroy'])->name('alliance.kingdom.roles.destroy');
        Route::post('/alliance/roster', [RosterController::class, 'store'])->name('alliance.roster.store');
        Route::patch('/alliance/roster/{entry}', [RosterController::class, 'update'])->name('alliance.roster.update');
        Route::post('/alliance/roster/{entry}/leave', [RosterController::class, 'leave'])->name('alliance.roster.leave');
        Route::post('/alliance/roster/{entry}/snapshots', [PlayerSnapshotController::class, 'store'])->name('alliance.roster.snapshots.store');
        Route::post('/alliance/roster/import/preview', [RosterCsvController::class, 'preview'])->name('alliance.roster.import.preview');
        Route::post('/alliance/roster/import/{import}/commit', [RosterCsvController::class, 'commit'])->name('alliance.roster.import.commit');
        Route::post('/alliance/kingdom-alliances', [KingdomAllianceController::class, 'store'])->name('alliance.kingdom-alliances.store');
        Route::patch('/alliance/kingdom-alliances/{tracking}', [KingdomAllianceController::class, 'update'])->name('alliance.kingdom-alliances.update');
        Route::post('/alliance/kingdom-alliances/{tracking}/archive', [KingdomAllianceController::class, 'archive'])->name('alliance.kingdom-alliances.archive');
        Route::post('/alliance/kingdom-alliances/{tracking}/observations', [KingdomAllianceObservationController::class, 'store'])->name('alliance.kingdom-alliances.observations.store');
        Route::post('/alliance/kingdom-alliances/{tracking}/observations/{observation}/invalidate', [KingdomAllianceObservationController::class, 'invalidate'])->name('alliance.kingdom-alliances.observations.invalidate');
        Route::post('/alliance/kingdom-alliances/{tracking}/diplomacy/transitions', [KingdomAllianceDiplomacyController::class, 'transition'])->name('alliance.kingdom-alliances.diplomacy.transition');
        Route::post('/alliance/kingdom-alliances/{tracking}/diplomacy/contacts', [KingdomAllianceDiplomacyContactController::class, 'store'])->name('alliance.kingdom-alliances.diplomacy.contacts.store');
        Route::patch('/alliance/kingdom-alliances/{tracking}/diplomacy/contacts/{contact}', [KingdomAllianceDiplomacyContactController::class, 'update'])->name('alliance.kingdom-alliances.diplomacy.contacts.update');
        Route::post('/alliance/kingdom-alliances/{tracking}/diplomacy/contacts/{contact}/deactivate', [KingdomAllianceDiplomacyContactController::class, 'deactivate'])->name('alliance.kingdom-alliances.diplomacy.contacts.deactivate');
        Route::post('/alliance/kingdom-ingestion/subscriptions', [KingdomIngestionController::class, 'store'])->name('alliance.kingdom-ingestion.subscriptions.store');
        Route::patch('/alliance/kingdom-ingestion/subscriptions/{subscription}/state', [KingdomIngestionController::class, 'transition'])->name('alliance.kingdom-ingestion.subscriptions.state');
        Route::post('/alliance/kingdom-ingestion/subscriptions/{subscription}/candidates/{candidate}/reject', [KingdomIngestionController::class, 'rejectCandidate'])->name('alliance.kingdom-ingestion.candidates.reject');
        Route::post('/alliance/kingdom-ingestion/subscriptions/{subscription}/candidates/{candidate}/replay', [KingdomIngestionController::class, 'replayCandidate'])->name('alliance.kingdom-ingestion.candidates.replay');
        Route::post('/alliance/kingdom-sharing/invitations', [KingdomIntelligenceSharingController::class, 'createInvitation'])->name('alliance.kingdom-sharing.invitations.store');
        Route::post('/alliance/kingdom-sharing/invitations/accept', [KingdomIntelligenceSharingController::class, 'acceptInvitation'])->name('alliance.kingdom-sharing.invitations.accept');
        Route::post('/alliance/kingdom-sharing/invitations/decline', [KingdomIntelligenceSharingController::class, 'declineInvitation'])->name('alliance.kingdom-sharing.invitations.decline');
        Route::post('/alliance/kingdom-sharing/{share}/revoke', [KingdomIntelligenceSharingController::class, 'revoke'])->name('alliance.kingdom-sharing.revoke');
        Route::post('/alliance/kingdom-sharing/{share}/leave', [KingdomIntelligenceSharingController::class, 'leave'])->name('alliance.kingdom-sharing.leave');
        Route::post('/alliance/kingdom-sharing/{share}/targets/{tracking}', [KingdomIntelligenceSharingController::class, 'addTarget'])->name('alliance.kingdom-sharing.targets.store');
        Route::post('/alliance/kingdom-sharing/{share}/targets/{target}/remove', [KingdomIntelligenceSharingController::class, 'removeTarget'])->name('alliance.kingdom-sharing.targets.remove');
        Route::post('/alliance/transfers/windows', [TransferPlanningController::class, 'storeWindow'])->name('alliance.transfers.windows.store');
        Route::patch('/alliance/transfers/windows/{window}', [TransferPlanningController::class, 'updateWindow'])->name('alliance.transfers.windows.update');
        Route::post('/alliance/transfers/windows/{window}/official-groups', [TransferPlanningController::class, 'storeGroup'])->name('alliance.transfers.official-groups.store');
        Route::post('/alliance/transfers/windows/{window}/conditions', [TransferPlanningController::class, 'storeCondition'])->name('alliance.transfers.conditions.store');
        Route::post('/alliance/transfers', [TransferPlanController::class, 'store'])->name('alliance.transfers.store');
        Route::post('/alliance/transfers/{plan}/open', [TransferPlanController::class, 'open'])->name('alliance.transfers.open');
        Route::post('/alliance/transfers/{plan}/lock', [TransferPlanController::class, 'lock'])->name('alliance.transfers.lock');
        Route::post('/alliance/transfers/{plan}/close', [TransferPlanController::class, 'close'])->name('alliance.transfers.close');
        Route::post('/alliance/transfers/{plan}/cancel', [TransferPlanController::class, 'cancel'])->name('alliance.transfers.cancel');
        Route::post('/alliance/transfers/{plan}/cohorts', [TransferCohortController::class, 'store'])->name('alliance.transfers.cohorts.store');
        Route::patch('/alliance/transfers/{plan}/cohorts/{cohort}', [TransferCohortController::class, 'update'])->name('alliance.transfers.cohorts.update');
        Route::post('/alliance/transfers/{plan}/cohorts/{cohort}/archive', [TransferCohortController::class, 'archive'])->name('alliance.transfers.cohorts.archive');
        Route::post('/alliance/transfers/{plan}/participants', [TransferParticipantController::class, 'store'])->name('alliance.transfers.participants.store');
        Route::patch('/alliance/transfers/{plan}/participants/{participant}', [TransferParticipantController::class, 'update'])->name('alliance.transfers.participants.update');
        Route::patch('/alliance/transfers/{plan}/participants/{participant}/cohort', [TransferCohortController::class, 'assignParticipant'])->name('alliance.transfers.participants.cohort');
        Route::post('/alliance/transfers/{plan}/participants/{participant}/observations', [TransferPlanningController::class, 'storeObservation'])->name('alliance.transfers.participants.observations.store');
        Route::patch('/alliance/transfers/{plan}/participants/{participant}/readiness', [TransferReadinessController::class, 'transition'])->name('alliance.transfers.participants.readiness');
        Route::post('/alliance/transfers/{plan}/participants/{participant}/blockers', [TransferReadinessController::class, 'storeBlocker'])->name('alliance.transfers.participants.blockers.store');
        Route::post('/alliance/transfers/{plan}/participants/{participant}/blockers/{blocker}/resolve', [TransferReadinessController::class, 'resolveBlocker'])->name('alliance.transfers.participants.blockers.resolve');
        Route::post('/alliance/transfers/{plan}/participants/{participant}/withdraw', [TransferParticipantController::class, 'withdraw'])->name('alliance.transfers.participants.withdraw');
        Route::post('/alliance/transfers/{plan}/participants/{participant}/complete', [TransferCompletionController::class, 'store'])->name('alliance.transfers.participants.complete');
    });
});
