import type { LocaleCode } from '../locales';

const en = {
  accountExperience: {
    account: {
      eyebrow: 'Account command',
      title: 'Account & security',
      intro: 'Manage your identity, verification, password, two-factor authentication, and active sessions.',
      passwordUpdated: 'Your password was updated and other authenticated sessions were revoked.',
      sessionsRevoked: 'Other authenticated sessions were signed out.',
      twoFactorDisabled: 'Two-factor authentication was disabled.',
      profileTitle: 'Profile',
      profileIntro: 'Changing your email address requires verification again.',
      timezone: 'Time zone',
      saveProfile: 'Save profile',
      emailVerification: 'Email verification',
      verified: 'Verified',
      pending: 'Pending',
      twoFactorState: 'Two-factor authentication',
      enabled: 'Enabled',
      setupPending: 'Setup pending',
      notEnabled: 'Not enabled',
      twoFactorTitle: 'Two-factor authentication',
      twoFactorIntro: 'Protect sign-in with a TOTP authenticator. Recovery codes are shown only when created or regenerated.',
      startSetup: 'Start setup',
      authenticatorSecret: 'Authenticator secret',
      provisioningUri: 'Provisioning URI',
      authenticationCode: 'Authentication code',
      confirm: 'Confirm',
      saveRecoveryCodes: 'Save these recovery codes now',
      recoveryIntro: 'Each code works once. Store them somewhere separate from this account.',
      regenerateRecoveryCodes: 'Regenerate recovery codes',
      disableTwoFactor: 'Disable two-factor authentication',
      passwordTitle: 'Change password',
      passwordIntro: 'Changing your password revokes personal access tokens and invalidates other authenticated sessions.',
      currentPassword: 'Current password',
      newPassword: 'New password',
      confirmNewPassword: 'Confirm new password',
      updatePassword: 'Update password',
      sessionsTitle: 'Other sessions',
      sessionsIntro: 'Revoke every authenticated session except this device.',
      signOutOthers: 'Sign out other devices',
      dangerTitle: 'Danger zone',
      deleteAccount: 'Account deletion',
    },
    deletion: {
      eyebrow: 'Account lifecycle',
      title: 'Account deletion',
      intro: 'Deletion uses a seven-day cooling-off period. Active alliance ownership, platform-administrator access, and legal holds can block processing. Processed accounts are anonymized instead of silently removing audit history.',
      currentRequest: 'Current request',
      status: 'Status',
      eligibleAt: 'Eligible at',
      requestedAt: 'Requested',
      processedAt: 'Processed',
      notYet: 'Not yet',
      requestTitle: 'Request deletion',
      requestIntro: 'Transfer ownership of any alliance you own first. Records subject to legal hold or required for security and audit integrity are retained in pseudonymized form.',
      requestButton: 'Request account deletion',
      confirm: 'Request account deletion? There is a seven-day cooling-off period and ownership/legal-hold checks apply.',
      requested: 'Your account deletion request was recorded.',
      backToAccount: 'Back to account & security',
    },
  },
} as const;

type AccountExperienceTree = {
  accountExperience: {
    account: { [K in keyof typeof en.accountExperience.account]: string };
    deletion: { [K in keyof typeof en.accountExperience.deletion]: string };
  };
};

export const accountExperienceMessages: Record<LocaleCode, AccountExperienceTree> = {
  en,
  ar: { accountExperience: { account: {
    eyebrow: 'إدارة الحساب', title: 'الحساب والأمان', intro: 'أدر هويتك والتحقق وكلمة المرور والمصادقة الثنائية والجلسات النشطة.', passwordUpdated: 'تم تحديث كلمة المرور وتسجيل خروج الجلسات الموثقة الأخرى.', sessionsRevoked: 'تم تسجيل خروج الجلسات الموثقة الأخرى.', twoFactorDisabled: 'تم تعطيل المصادقة الثنائية.', profileTitle: 'الملف الشخصي', profileIntro: 'يتطلب تغيير البريد الإلكتروني التحقق منه من جديد.', timezone: 'المنطقة الزمنية', saveProfile: 'حفظ الملف الشخصي', emailVerification: 'التحقق من البريد الإلكتروني', verified: 'تم التحقق', pending: 'معلّق', twoFactorState: 'المصادقة الثنائية', enabled: 'مفعّلة', setupPending: 'الإعداد معلّق', notEnabled: 'غير مفعّلة', twoFactorTitle: 'المصادقة الثنائية', twoFactorIntro: 'احمِ تسجيل الدخول باستخدام تطبيق مصادقة TOTP. تظهر رموز الاسترداد فقط عند إنشائها أو إعادة توليدها.', startSetup: 'بدء الإعداد', authenticatorSecret: 'سر تطبيق المصادقة', provisioningUri: 'رابط التهيئة', authenticationCode: 'رمز المصادقة', confirm: 'تأكيد', saveRecoveryCodes: 'احفظ رموز الاسترداد الآن', recoveryIntro: 'يعمل كل رمز مرة واحدة. خزّنها بعيداً عن هذا الحساب.', regenerateRecoveryCodes: 'إعادة توليد رموز الاسترداد', disableTwoFactor: 'تعطيل المصادقة الثنائية', passwordTitle: 'تغيير كلمة المرور', passwordIntro: 'يؤدي تغيير كلمة المرور إلى إلغاء رموز الوصول الشخصية والجلسات الموثقة الأخرى.', currentPassword: 'كلمة المرور الحالية', newPassword: 'كلمة المرور الجديدة', confirmNewPassword: 'تأكيد كلمة المرور الجديدة', updatePassword: 'تحديث كلمة المرور', sessionsTitle: 'الجلسات الأخرى', sessionsIntro: 'ألغِ كل جلسة موثقة باستثناء هذا الجهاز.', signOutOthers: 'تسجيل خروج الأجهزة الأخرى', dangerTitle: 'منطقة حساسة', deleteAccount: 'حذف الحساب',
  }, deletion: {
    eyebrow: 'دورة حياة الحساب', title: 'حذف الحساب', intro: 'يتضمن الحذف فترة انتظار سبعة أيام. قد تمنع ملكية تحالف نشط أو صلاحيات مسؤول المنصة أو الحجز القانوني تنفيذ الطلب. يتم إخفاء هوية الحسابات المعالجة بدلاً من حذف سجل التدقيق.', currentRequest: 'الطلب الحالي', status: 'الحالة', eligibleAt: 'مؤهل في', requestedAt: 'تاريخ الطلب', processedAt: 'تمت المعالجة', notYet: 'ليس بعد', requestTitle: 'طلب الحذف', requestIntro: 'انقل ملكية أي تحالف تملكه أولاً. تُحتفظ السجلات الخاضعة لحجز قانوني أو المطلوبة للأمان والتدقيق بصيغة مستعارة.', requestButton: 'طلب حذف الحساب', confirm: 'هل تريد طلب حذف الحساب؟ توجد فترة انتظار سبعة أيام وتُطبّق فحوص الملكية والحجز القانوني.', requested: 'تم تسجيل طلب حذف حسابك.', backToAccount: 'العودة إلى الحساب والأمان',
  } } },
  de: { accountExperience: { account: {
    eyebrow: 'Kontosteuerung', title: 'Konto & Sicherheit', intro: 'Verwalte Identität, Verifizierung, Passwort, Zwei-Faktor-Authentifizierung und aktive Sitzungen.', passwordUpdated: 'Dein Passwort wurde aktualisiert und andere authentifizierte Sitzungen wurden beendet.', sessionsRevoked: 'Andere authentifizierte Sitzungen wurden abgemeldet.', twoFactorDisabled: 'Die Zwei-Faktor-Authentifizierung wurde deaktiviert.', profileTitle: 'Profil', profileIntro: 'Nach einer Änderung der E-Mail-Adresse ist eine erneute Verifizierung erforderlich.', timezone: 'Zeitzone', saveProfile: 'Profil speichern', emailVerification: 'E-Mail-Verifizierung', verified: 'Verifiziert', pending: 'Ausstehend', twoFactorState: 'Zwei-Faktor-Authentifizierung', enabled: 'Aktiviert', setupPending: 'Einrichtung ausstehend', notEnabled: 'Nicht aktiviert', twoFactorTitle: 'Zwei-Faktor-Authentifizierung', twoFactorIntro: 'Schütze die Anmeldung mit einem TOTP-Authenticator. Wiederherstellungscodes werden nur bei Erstellung oder Neugenerierung angezeigt.', startSetup: 'Einrichtung starten', authenticatorSecret: 'Authenticator-Geheimnis', provisioningUri: 'Bereitstellungs-URI', authenticationCode: 'Authentifizierungscode', confirm: 'Bestätigen', saveRecoveryCodes: 'Diese Wiederherstellungscodes jetzt speichern', recoveryIntro: 'Jeder Code funktioniert einmal. Bewahre sie getrennt von diesem Konto auf.', regenerateRecoveryCodes: 'Wiederherstellungscodes neu erzeugen', disableTwoFactor: 'Zwei-Faktor-Authentifizierung deaktivieren', passwordTitle: 'Passwort ändern', passwordIntro: 'Eine Passwortänderung widerruft persönliche Zugriffstoken und beendet andere authentifizierte Sitzungen.', currentPassword: 'Aktuelles Passwort', newPassword: 'Neues Passwort', confirmNewPassword: 'Neues Passwort bestätigen', updatePassword: 'Passwort aktualisieren', sessionsTitle: 'Andere Sitzungen', sessionsIntro: 'Beende alle authentifizierten Sitzungen außer diesem Gerät.', signOutOthers: 'Andere Geräte abmelden', dangerTitle: 'Gefahrenbereich', deleteAccount: 'Konto löschen',
  }, deletion: {
    eyebrow: 'Kontolebenszyklus', title: 'Konto löschen', intro: 'Für die Löschung gilt eine siebentägige Wartefrist. Aktiver Allianzbesitz, Plattformadministrator-Zugriff oder rechtliche Sperren können die Verarbeitung blockieren. Verarbeitete Konten werden anonymisiert, statt die Audit-Historie zu entfernen.', currentRequest: 'Aktuelle Anfrage', status: 'Status', eligibleAt: 'Berechtigt ab', requestedAt: 'Angefordert', processedAt: 'Verarbeitet', notYet: 'Noch nicht', requestTitle: 'Löschung anfordern', requestIntro: 'Übertrage zuerst die Eigentümerschaft aller Allianzen. Rechtlich gesperrte oder für Sicherheit und Audit notwendige Datensätze bleiben pseudonymisiert erhalten.', requestButton: 'Kontolöschung anfordern', confirm: 'Kontolöschung anfordern? Es gilt eine siebentägige Wartefrist sowie Eigentums- und Legal-Hold-Prüfungen.', requested: 'Deine Kontolöschungsanfrage wurde erfasst.', backToAccount: 'Zurück zu Konto & Sicherheit',
  } } },
  es: { accountExperience: { account: {
    eyebrow: 'Control de cuenta', title: 'Cuenta y seguridad', intro: 'Gestiona tu identidad, verificación, contraseña, autenticación de dos factores y sesiones activas.', passwordUpdated: 'Tu contraseña se actualizó y se cerraron las demás sesiones autenticadas.', sessionsRevoked: 'Se cerraron las demás sesiones autenticadas.', twoFactorDisabled: 'La autenticación de dos factores fue desactivada.', profileTitle: 'Perfil', profileIntro: 'Cambiar tu correo electrónico requiere verificarlo de nuevo.', timezone: 'Zona horaria', saveProfile: 'Guardar perfil', emailVerification: 'Verificación de correo', verified: 'Verificado', pending: 'Pendiente', twoFactorState: 'Autenticación de dos factores', enabled: 'Activada', setupPending: 'Configuración pendiente', notEnabled: 'No activada', twoFactorTitle: 'Autenticación de dos factores', twoFactorIntro: 'Protege el inicio de sesión con un autenticador TOTP. Los códigos de recuperación solo se muestran al crearlos o regenerarlos.', startSetup: 'Iniciar configuración', authenticatorSecret: 'Secreto del autenticador', provisioningUri: 'URI de aprovisionamiento', authenticationCode: 'Código de autenticación', confirm: 'Confirmar', saveRecoveryCodes: 'Guarda estos códigos de recuperación ahora', recoveryIntro: 'Cada código funciona una sola vez. Guárdalos por separado de esta cuenta.', regenerateRecoveryCodes: 'Regenerar códigos de recuperación', disableTwoFactor: 'Desactivar autenticación de dos factores', passwordTitle: 'Cambiar contraseña', passwordIntro: 'Cambiar la contraseña revoca los tokens de acceso personales e invalida otras sesiones autenticadas.', currentPassword: 'Contraseña actual', newPassword: 'Nueva contraseña', confirmNewPassword: 'Confirmar nueva contraseña', updatePassword: 'Actualizar contraseña', sessionsTitle: 'Otras sesiones', sessionsIntro: 'Revoca todas las sesiones autenticadas excepto este dispositivo.', signOutOthers: 'Cerrar sesión en otros dispositivos', dangerTitle: 'Zona de riesgo', deleteAccount: 'Eliminar cuenta',
  }, deletion: {
    eyebrow: 'Ciclo de vida de la cuenta', title: 'Eliminar cuenta', intro: 'La eliminación tiene un periodo de espera de siete días. La propiedad activa de una alianza, el acceso de administrador de plataforma y las retenciones legales pueden bloquear el proceso. Las cuentas procesadas se anonimizan en lugar de borrar el historial de auditoría.', currentRequest: 'Solicitud actual', status: 'Estado', eligibleAt: 'Elegible el', requestedAt: 'Solicitado', processedAt: 'Procesado', notYet: 'Todavía no', requestTitle: 'Solicitar eliminación', requestIntro: 'Transfiere primero la propiedad de cualquier alianza. Los registros sujetos a retención legal o necesarios para seguridad y auditoría se conservan seudonimizados.', requestButton: 'Solicitar eliminación de cuenta', confirm: '¿Solicitar la eliminación de la cuenta? Hay un periodo de espera de siete días y se aplican comprobaciones de propiedad y retención legal.', requested: 'Se registró tu solicitud de eliminación de cuenta.', backToAccount: 'Volver a cuenta y seguridad',
  } } },
  fr: { accountExperience: { account: {
    eyebrow: 'Gestion du compte', title: 'Compte et sécurité', intro: 'Gérez votre identité, la vérification, le mot de passe, l’authentification à deux facteurs et les sessions actives.', passwordUpdated: 'Votre mot de passe a été mis à jour et les autres sessions authentifiées ont été révoquées.', sessionsRevoked: 'Les autres sessions authentifiées ont été déconnectées.', twoFactorDisabled: 'L’authentification à deux facteurs a été désactivée.', profileTitle: 'Profil', profileIntro: 'Modifier votre adresse e-mail nécessite une nouvelle vérification.', timezone: 'Fuseau horaire', saveProfile: 'Enregistrer le profil', emailVerification: 'Vérification de l’e-mail', verified: 'Vérifié', pending: 'En attente', twoFactorState: 'Authentification à deux facteurs', enabled: 'Activée', setupPending: 'Configuration en attente', notEnabled: 'Non activée', twoFactorTitle: 'Authentification à deux facteurs', twoFactorIntro: 'Protégez la connexion avec un authentificateur TOTP. Les codes de récupération ne sont affichés qu’à leur création ou régénération.', startSetup: 'Commencer la configuration', authenticatorSecret: 'Secret de l’authentificateur', provisioningUri: 'URI de configuration', authenticationCode: 'Code d’authentification', confirm: 'Confirmer', saveRecoveryCodes: 'Enregistrez ces codes de récupération maintenant', recoveryIntro: 'Chaque code ne fonctionne qu’une fois. Conservez-les séparément de ce compte.', regenerateRecoveryCodes: 'Régénérer les codes de récupération', disableTwoFactor: 'Désactiver l’authentification à deux facteurs', passwordTitle: 'Changer le mot de passe', passwordIntro: 'Changer le mot de passe révoque les jetons d’accès personnels et invalide les autres sessions authentifiées.', currentPassword: 'Mot de passe actuel', newPassword: 'Nouveau mot de passe', confirmNewPassword: 'Confirmer le nouveau mot de passe', updatePassword: 'Mettre à jour le mot de passe', sessionsTitle: 'Autres sessions', sessionsIntro: 'Révoquez toutes les sessions authentifiées sauf cet appareil.', signOutOthers: 'Déconnecter les autres appareils', dangerTitle: 'Zone sensible', deleteAccount: 'Suppression du compte',
  }, deletion: {
    eyebrow: 'Cycle de vie du compte', title: 'Suppression du compte', intro: 'La suppression comprend un délai de réflexion de sept jours. La propriété active d’une alliance, l’accès administrateur de plateforme ou une conservation légale peuvent bloquer le traitement. Les comptes traités sont anonymisés plutôt que d’effacer l’historique d’audit.', currentRequest: 'Demande actuelle', status: 'Statut', eligibleAt: 'Éligible le', requestedAt: 'Demandé', processedAt: 'Traité', notYet: 'Pas encore', requestTitle: 'Demander la suppression', requestIntro: 'Transférez d’abord la propriété de toute alliance. Les enregistrements soumis à une conservation légale ou requis pour la sécurité et l’audit restent pseudonymisés.', requestButton: 'Demander la suppression du compte', confirm: 'Demander la suppression du compte ? Un délai de sept jours et des contrôles de propriété/conservation légale s’appliquent.', requested: 'Votre demande de suppression de compte a été enregistrée.', backToAccount: 'Retour au compte et sécurité',
  } } },
  id: { accountExperience: { account: {
    eyebrow: 'Kontrol akun', title: 'Akun & keamanan', intro: 'Kelola identitas, verifikasi, kata sandi, autentikasi dua faktor, dan sesi aktif Anda.', passwordUpdated: 'Kata sandi diperbarui dan sesi terautentikasi lainnya dicabut.', sessionsRevoked: 'Sesi terautentikasi lainnya telah keluar.', twoFactorDisabled: 'Autentikasi dua faktor dinonaktifkan.', profileTitle: 'Profil', profileIntro: 'Mengubah email memerlukan verifikasi ulang.', timezone: 'Zona waktu', saveProfile: 'Simpan profil', emailVerification: 'Verifikasi email', verified: 'Terverifikasi', pending: 'Tertunda', twoFactorState: 'Autentikasi dua faktor', enabled: 'Aktif', setupPending: 'Penyiapan tertunda', notEnabled: 'Tidak aktif', twoFactorTitle: 'Autentikasi dua faktor', twoFactorIntro: 'Lindungi login dengan autentikator TOTP. Kode pemulihan hanya ditampilkan saat dibuat atau dibuat ulang.', startSetup: 'Mulai penyiapan', authenticatorSecret: 'Rahasia autentikator', provisioningUri: 'URI penyediaan', authenticationCode: 'Kode autentikasi', confirm: 'Konfirmasi', saveRecoveryCodes: 'Simpan kode pemulihan ini sekarang', recoveryIntro: 'Setiap kode hanya berlaku sekali. Simpan terpisah dari akun ini.', regenerateRecoveryCodes: 'Buat ulang kode pemulihan', disableTwoFactor: 'Nonaktifkan autentikasi dua faktor', passwordTitle: 'Ubah kata sandi', passwordIntro: 'Mengubah kata sandi mencabut token akses pribadi dan membatalkan sesi terautentikasi lainnya.', currentPassword: 'Kata sandi saat ini', newPassword: 'Kata sandi baru', confirmNewPassword: 'Konfirmasi kata sandi baru', updatePassword: 'Perbarui kata sandi', sessionsTitle: 'Sesi lain', sessionsIntro: 'Cabut semua sesi terautentikasi kecuali perangkat ini.', signOutOthers: 'Keluar dari perangkat lain', dangerTitle: 'Zona berbahaya', deleteAccount: 'Hapus akun',
  }, deletion: {
    eyebrow: 'Siklus akun', title: 'Hapus akun', intro: 'Penghapusan memiliki masa tunggu tujuh hari. Kepemilikan aliansi aktif, akses administrator platform, dan penahanan hukum dapat memblokir proses. Akun yang diproses dianonimkan tanpa menghapus riwayat audit.', currentRequest: 'Permintaan saat ini', status: 'Status', eligibleAt: 'Memenuhi syarat pada', requestedAt: 'Diminta', processedAt: 'Diproses', notYet: 'Belum', requestTitle: 'Minta penghapusan', requestIntro: 'Transfer kepemilikan aliansi terlebih dahulu. Catatan yang terkena penahanan hukum atau diperlukan untuk keamanan/audit tetap disimpan dalam bentuk pseudonim.', requestButton: 'Minta penghapusan akun', confirm: 'Minta penghapusan akun? Ada masa tunggu tujuh hari serta pemeriksaan kepemilikan dan penahanan hukum.', requested: 'Permintaan penghapusan akun Anda telah dicatat.', backToAccount: 'Kembali ke akun & keamanan',
  } } },
  it: { accountExperience: { account: {
    eyebrow: 'Gestione account', title: 'Account e sicurezza', intro: 'Gestisci identità, verifica, password, autenticazione a due fattori e sessioni attive.', passwordUpdated: 'La password è stata aggiornata e le altre sessioni autenticate sono state revocate.', sessionsRevoked: 'Le altre sessioni autenticate sono state disconnesse.', twoFactorDisabled: 'L’autenticazione a due fattori è stata disattivata.', profileTitle: 'Profilo', profileIntro: 'La modifica dell’e-mail richiede una nuova verifica.', timezone: 'Fuso orario', saveProfile: 'Salva profilo', emailVerification: 'Verifica e-mail', verified: 'Verificata', pending: 'In attesa', twoFactorState: 'Autenticazione a due fattori', enabled: 'Attiva', setupPending: 'Configurazione in sospeso', notEnabled: 'Non attiva', twoFactorTitle: 'Autenticazione a due fattori', twoFactorIntro: 'Proteggi l’accesso con un autenticatore TOTP. I codici di recupero vengono mostrati solo quando creati o rigenerati.', startSetup: 'Avvia configurazione', authenticatorSecret: 'Segreto autenticatore', provisioningUri: 'URI di provisioning', authenticationCode: 'Codice di autenticazione', confirm: 'Conferma', saveRecoveryCodes: 'Salva ora questi codici di recupero', recoveryIntro: 'Ogni codice funziona una sola volta. Conservali separatamente da questo account.', regenerateRecoveryCodes: 'Rigenera codici di recupero', disableTwoFactor: 'Disattiva autenticazione a due fattori', passwordTitle: 'Cambia password', passwordIntro: 'La modifica della password revoca i token di accesso personali e invalida le altre sessioni autenticate.', currentPassword: 'Password attuale', newPassword: 'Nuova password', confirmNewPassword: 'Conferma nuova password', updatePassword: 'Aggiorna password', sessionsTitle: 'Altre sessioni', sessionsIntro: 'Revoca tutte le sessioni autenticate tranne questo dispositivo.', signOutOthers: 'Disconnetti gli altri dispositivi', dangerTitle: 'Zona pericolosa', deleteAccount: 'Eliminazione account',
  }, deletion: {
    eyebrow: 'Ciclo di vita account', title: 'Eliminazione account', intro: 'L’eliminazione prevede sette giorni di attesa. La proprietà attiva di un’alleanza, l’accesso amministratore della piattaforma e i blocchi legali possono impedirne l’elaborazione. Gli account elaborati vengono anonimizzati senza rimuovere la cronologia di audit.', currentRequest: 'Richiesta corrente', status: 'Stato', eligibleAt: 'Idoneo dal', requestedAt: 'Richiesto', processedAt: 'Elaborato', notYet: 'Non ancora', requestTitle: 'Richiedi eliminazione', requestIntro: 'Trasferisci prima la proprietà di ogni alleanza. I record soggetti a blocco legale o necessari per sicurezza e audit restano pseudonimizzati.', requestButton: 'Richiedi eliminazione account', confirm: 'Richiedere l’eliminazione dell’account? Si applicano sette giorni di attesa e controlli su proprietà e blocchi legali.', requested: 'La richiesta di eliminazione dell’account è stata registrata.', backToAccount: 'Torna ad account e sicurezza',
  } } },
  ja: { accountExperience: { account: {
    eyebrow: 'アカウント管理', title: 'アカウントとセキュリティ', intro: '本人情報、メール認証、パスワード、二要素認証、アクティブなセッションを管理します。', passwordUpdated: 'パスワードを更新し、他の認証済みセッションを無効にしました。', sessionsRevoked: '他の認証済みセッションからサインアウトしました。', twoFactorDisabled: '二要素認証を無効にしました。', profileTitle: 'プロフィール', profileIntro: 'メールアドレスを変更すると再認証が必要です。', timezone: 'タイムゾーン', saveProfile: 'プロフィールを保存', emailVerification: 'メール認証', verified: '認証済み', pending: '保留中', twoFactorState: '二要素認証', enabled: '有効', setupPending: '設定保留中', notEnabled: '無効', twoFactorTitle: '二要素認証', twoFactorIntro: 'TOTP認証アプリでサインインを保護します。リカバリーコードは作成または再生成時のみ表示されます。', startSetup: '設定を開始', authenticatorSecret: '認証アプリのシークレット', provisioningUri: 'プロビジョニングURI', authenticationCode: '認証コード', confirm: '確認', saveRecoveryCodes: 'リカバリーコードを今すぐ保存', recoveryIntro: '各コードは1回だけ使用できます。このアカウントとは別の場所に保管してください。', regenerateRecoveryCodes: 'リカバリーコードを再生成', disableTwoFactor: '二要素認証を無効化', passwordTitle: 'パスワード変更', passwordIntro: 'パスワードを変更すると個人アクセストークンが失効し、他の認証済みセッションも無効になります。', currentPassword: '現在のパスワード', newPassword: '新しいパスワード', confirmNewPassword: '新しいパスワードを確認', updatePassword: 'パスワードを更新', sessionsTitle: 'その他のセッション', sessionsIntro: 'この端末以外の認証済みセッションをすべて無効にします。', signOutOthers: '他の端末からサインアウト', dangerTitle: '危険な操作', deleteAccount: 'アカウント削除',
  }, deletion: {
    eyebrow: 'アカウントライフサイクル', title: 'アカウント削除', intro: '削除には7日間のクーリングオフ期間があります。アクティブな同盟所有権、プラットフォーム管理者権限、法的保留により処理が停止する場合があります。処理済みアカウントは監査履歴を消さず匿名化されます。', currentRequest: '現在の申請', status: '状態', eligibleAt: '処理可能日時', requestedAt: '申請日時', processedAt: '処理日時', notYet: '未処理', requestTitle: '削除を申請', requestIntro: '所有する同盟の所有権を先に移してください。法的保留またはセキュリティ・監査に必要な記録は仮名化して保持されます。', requestButton: 'アカウント削除を申請', confirm: 'アカウント削除を申請しますか？7日間の待機期間と所有権・法的保留の確認があります。', requested: 'アカウント削除申請を記録しました。', backToAccount: 'アカウントとセキュリティに戻る',
  } } },
  ko: { accountExperience: { account: {
    eyebrow: '계정 관리', title: '계정 및 보안', intro: '신원, 이메일 인증, 비밀번호, 2단계 인증 및 활성 세션을 관리합니다.', passwordUpdated: '비밀번호가 업데이트되었고 다른 인증 세션이 해제되었습니다.', sessionsRevoked: '다른 인증 세션에서 로그아웃했습니다.', twoFactorDisabled: '2단계 인증이 비활성화되었습니다.', profileTitle: '프로필', profileIntro: '이메일 주소를 변경하면 다시 인증해야 합니다.', timezone: '시간대', saveProfile: '프로필 저장', emailVerification: '이메일 인증', verified: '인증됨', pending: '대기 중', twoFactorState: '2단계 인증', enabled: '활성화', setupPending: '설정 대기 중', notEnabled: '비활성화', twoFactorTitle: '2단계 인증', twoFactorIntro: 'TOTP 인증 앱으로 로그인을 보호합니다. 복구 코드는 생성 또는 재생성할 때만 표시됩니다.', startSetup: '설정 시작', authenticatorSecret: '인증 앱 비밀키', provisioningUri: '프로비저닝 URI', authenticationCode: '인증 코드', confirm: '확인', saveRecoveryCodes: '복구 코드를 지금 저장하세요', recoveryIntro: '각 코드는 한 번만 사용할 수 있습니다. 이 계정과 분리된 곳에 보관하세요.', regenerateRecoveryCodes: '복구 코드 재생성', disableTwoFactor: '2단계 인증 비활성화', passwordTitle: '비밀번호 변경', passwordIntro: '비밀번호를 변경하면 개인 액세스 토큰이 취소되고 다른 인증 세션이 무효화됩니다.', currentPassword: '현재 비밀번호', newPassword: '새 비밀번호', confirmNewPassword: '새 비밀번호 확인', updatePassword: '비밀번호 업데이트', sessionsTitle: '다른 세션', sessionsIntro: '이 기기를 제외한 모든 인증 세션을 취소합니다.', signOutOthers: '다른 기기에서 로그아웃', dangerTitle: '위험 구역', deleteAccount: '계정 삭제',
  }, deletion: {
    eyebrow: '계정 수명 주기', title: '계정 삭제', intro: '삭제에는 7일의 유예 기간이 있습니다. 활성 동맹 소유권, 플랫폼 관리자 접근, 법적 보존 조치가 처리를 막을 수 있습니다. 처리된 계정은 감사 기록을 삭제하지 않고 익명화됩니다.', currentRequest: '현재 요청', status: '상태', eligibleAt: '처리 가능 시각', requestedAt: '요청 시각', processedAt: '처리 시각', notYet: '아직', requestTitle: '삭제 요청', requestIntro: '소유한 동맹의 소유권을 먼저 이전하세요. 법적 보존 또는 보안·감사에 필요한 기록은 가명 처리 형태로 유지됩니다.', requestButton: '계정 삭제 요청', confirm: '계정 삭제를 요청하시겠습니까? 7일의 유예 기간과 소유권/법적 보존 확인이 적용됩니다.', requested: '계정 삭제 요청이 기록되었습니다.', backToAccount: '계정 및 보안으로 돌아가기',
  } } },
  pl: { accountExperience: { account: {
    eyebrow: 'Zarządzanie kontem', title: 'Konto i bezpieczeństwo', intro: 'Zarządzaj tożsamością, weryfikacją, hasłem, uwierzytelnianiem dwuskładnikowym i aktywnymi sesjami.', passwordUpdated: 'Hasło zostało zaktualizowane, a pozostałe uwierzytelnione sesje unieważnione.', sessionsRevoked: 'Pozostałe uwierzytelnione sesje zostały wylogowane.', twoFactorDisabled: 'Uwierzytelnianie dwuskładnikowe zostało wyłączone.', profileTitle: 'Profil', profileIntro: 'Zmiana adresu e-mail wymaga ponownej weryfikacji.', timezone: 'Strefa czasowa', saveProfile: 'Zapisz profil', emailVerification: 'Weryfikacja e-mail', verified: 'Zweryfikowano', pending: 'Oczekuje', twoFactorState: 'Uwierzytelnianie dwuskładnikowe', enabled: 'Włączone', setupPending: 'Konfiguracja oczekuje', notEnabled: 'Wyłączone', twoFactorTitle: 'Uwierzytelnianie dwuskładnikowe', twoFactorIntro: 'Chroń logowanie za pomocą aplikacji TOTP. Kody odzyskiwania są wyświetlane tylko po utworzeniu lub ponownym wygenerowaniu.', startSetup: 'Rozpocznij konfigurację', authenticatorSecret: 'Sekret aplikacji uwierzytelniającej', provisioningUri: 'URI konfiguracji', authenticationCode: 'Kod uwierzytelniający', confirm: 'Potwierdź', saveRecoveryCodes: 'Zapisz teraz kody odzyskiwania', recoveryIntro: 'Każdy kod działa tylko raz. Przechowuj je oddzielnie od tego konta.', regenerateRecoveryCodes: 'Wygeneruj ponownie kody odzyskiwania', disableTwoFactor: 'Wyłącz uwierzytelnianie dwuskładnikowe', passwordTitle: 'Zmień hasło', passwordIntro: 'Zmiana hasła unieważnia osobiste tokeny dostępu i inne uwierzytelnione sesje.', currentPassword: 'Aktualne hasło', newPassword: 'Nowe hasło', confirmNewPassword: 'Potwierdź nowe hasło', updatePassword: 'Zaktualizuj hasło', sessionsTitle: 'Inne sesje', sessionsIntro: 'Unieważnij wszystkie uwierzytelnione sesje poza tym urządzeniem.', signOutOthers: 'Wyloguj inne urządzenia', dangerTitle: 'Strefa ryzyka', deleteAccount: 'Usuwanie konta',
  }, deletion: {
    eyebrow: 'Cykl życia konta', title: 'Usuwanie konta', intro: 'Usunięcie obejmuje siedmiodniowy okres oczekiwania. Aktywna własność sojuszu, dostęp administratora platformy i blokady prawne mogą zatrzymać proces. Przetworzone konta są anonimizowane bez usuwania historii audytu.', currentRequest: 'Bieżący wniosek', status: 'Status', eligibleAt: 'Możliwe od', requestedAt: 'Zgłoszono', processedAt: 'Przetworzono', notYet: 'Jeszcze nie', requestTitle: 'Poproś o usunięcie', requestIntro: 'Najpierw przenieś własność wszystkich sojuszy. Zapisy objęte blokadą prawną lub potrzebne do bezpieczeństwa i audytu pozostają w formie pseudonimizowanej.', requestButton: 'Poproś o usunięcie konta', confirm: 'Poprosić o usunięcie konta? Obowiązuje siedmiodniowy okres oczekiwania oraz kontrole własności i blokad prawnych.', requested: 'Wniosek o usunięcie konta został zapisany.', backToAccount: 'Wróć do konta i bezpieczeństwa',
  } } },
  'pt-BR': { accountExperience: { account: {
    eyebrow: 'Comando da conta', title: 'Conta e segurança', intro: 'Gerencie sua identidade, verificação, senha, autenticação em dois fatores e sessões ativas.', passwordUpdated: 'Sua senha foi atualizada e as outras sessões autenticadas foram revogadas.', sessionsRevoked: 'As outras sessões autenticadas foram encerradas.', twoFactorDisabled: 'A autenticação em dois fatores foi desativada.', profileTitle: 'Perfil', profileIntro: 'Alterar seu e-mail exige uma nova verificação.', timezone: 'Fuso horário', saveProfile: 'Salvar perfil', emailVerification: 'Verificação de e-mail', verified: 'Verificado', pending: 'Pendente', twoFactorState: 'Autenticação em dois fatores', enabled: 'Ativada', setupPending: 'Configuração pendente', notEnabled: 'Não ativada', twoFactorTitle: 'Autenticação em dois fatores', twoFactorIntro: 'Proteja o login com um autenticador TOTP. Os códigos de recuperação só aparecem quando são criados ou regenerados.', startSetup: 'Iniciar configuração', authenticatorSecret: 'Segredo do autenticador', provisioningUri: 'URI de provisionamento', authenticationCode: 'Código de autenticação', confirm: 'Confirmar', saveRecoveryCodes: 'Salve estes códigos de recuperação agora', recoveryIntro: 'Cada código funciona uma vez. Guarde-os em um local separado desta conta.', regenerateRecoveryCodes: 'Regenerar códigos de recuperação', disableTwoFactor: 'Desativar autenticação em dois fatores', passwordTitle: 'Alterar senha', passwordIntro: 'Alterar sua senha revoga tokens de acesso pessoais e invalida outras sessões autenticadas.', currentPassword: 'Senha atual', newPassword: 'Nova senha', confirmNewPassword: 'Confirmar nova senha', updatePassword: 'Atualizar senha', sessionsTitle: 'Outras sessões', sessionsIntro: 'Revogue todas as sessões autenticadas, exceto este dispositivo.', signOutOthers: 'Sair dos outros dispositivos', dangerTitle: 'Zona de risco', deleteAccount: 'Exclusão da conta',
  }, deletion: {
    eyebrow: 'Ciclo de vida da conta', title: 'Exclusão da conta', intro: 'A exclusão tem um período de espera de sete dias. Propriedade ativa de aliança, acesso de administrador da plataforma e retenções legais podem bloquear o processamento. Contas processadas são anonimizadas em vez de remover o histórico de auditoria.', currentRequest: 'Solicitação atual', status: 'Status', eligibleAt: 'Elegível em', requestedAt: 'Solicitado em', processedAt: 'Processado em', notYet: 'Ainda não', requestTitle: 'Solicitar exclusão', requestIntro: 'Transfira primeiro a propriedade de qualquer aliança. Registros sujeitos a retenção legal ou necessários para segurança e auditoria permanecem pseudonimizados.', requestButton: 'Solicitar exclusão da conta', confirm: 'Solicitar exclusão da conta? Há um período de espera de sete dias e verificações de propriedade e retenção legal.', requested: 'Sua solicitação de exclusão da conta foi registrada.', backToAccount: 'Voltar para conta e segurança',
  } } },
  ru: { accountExperience: { account: {
    eyebrow: 'Управление аккаунтом', title: 'Аккаунт и безопасность', intro: 'Управляйте профилем, подтверждением, паролем, двухфакторной аутентификацией и активными сессиями.', passwordUpdated: 'Пароль обновлён, другие авторизованные сессии отозваны.', sessionsRevoked: 'Другие авторизованные сессии завершены.', twoFactorDisabled: 'Двухфакторная аутентификация отключена.', profileTitle: 'Профиль', profileIntro: 'После изменения электронной почты потребуется повторное подтверждение.', timezone: 'Часовой пояс', saveProfile: 'Сохранить профиль', emailVerification: 'Подтверждение почты', verified: 'Подтверждено', pending: 'Ожидается', twoFactorState: 'Двухфакторная аутентификация', enabled: 'Включена', setupPending: 'Настройка не завершена', notEnabled: 'Не включена', twoFactorTitle: 'Двухфакторная аутентификация', twoFactorIntro: 'Защитите вход приложением TOTP. Коды восстановления отображаются только при создании или повторной генерации.', startSetup: 'Начать настройку', authenticatorSecret: 'Секрет аутентификатора', provisioningUri: 'URI настройки', authenticationCode: 'Код аутентификации', confirm: 'Подтвердить', saveRecoveryCodes: 'Сохраните коды восстановления сейчас', recoveryIntro: 'Каждый код работает один раз. Храните их отдельно от этого аккаунта.', regenerateRecoveryCodes: 'Создать новые коды восстановления', disableTwoFactor: 'Отключить двухфакторную аутентификацию', passwordTitle: 'Изменить пароль', passwordIntro: 'Смена пароля отзывает персональные токены доступа и завершает другие авторизованные сессии.', currentPassword: 'Текущий пароль', newPassword: 'Новый пароль', confirmNewPassword: 'Подтвердите новый пароль', updatePassword: 'Обновить пароль', sessionsTitle: 'Другие сессии', sessionsIntro: 'Отозвать все авторизованные сессии, кроме этого устройства.', signOutOthers: 'Выйти на других устройствах', dangerTitle: 'Опасная зона', deleteAccount: 'Удаление аккаунта',
  }, deletion: {
    eyebrow: 'Жизненный цикл аккаунта', title: 'Удаление аккаунта', intro: 'Удаление включает семидневный период ожидания. Активное владение альянсом, права администратора платформы и юридические ограничения могут заблокировать обработку. Обработанные аккаунты анонимизируются без удаления истории аудита.', currentRequest: 'Текущий запрос', status: 'Статус', eligibleAt: 'Можно обработать с', requestedAt: 'Запрошено', processedAt: 'Обработано', notYet: 'Ещё нет', requestTitle: 'Запросить удаление', requestIntro: 'Сначала передайте владение всеми альянсами. Записи под юридическим ограничением или необходимые для безопасности и аудита сохраняются в псевдонимизированном виде.', requestButton: 'Запросить удаление аккаунта', confirm: 'Запросить удаление аккаунта? Действует семидневный период ожидания и проверки владения/юридических ограничений.', requested: 'Запрос на удаление аккаунта зарегистрирован.', backToAccount: 'Назад к аккаунту и безопасности',
  } } },
  th: { accountExperience: { account: {
    eyebrow: 'การจัดการบัญชี', title: 'บัญชีและความปลอดภัย', intro: 'จัดการตัวตน การยืนยัน อีเมล รหัสผ่าน การยืนยันสองขั้นตอน และเซสชันที่ใช้งานอยู่', passwordUpdated: 'อัปเดตรหัสผ่านแล้วและยกเลิกเซสชันที่ยืนยันตัวตนอื่น ๆ', sessionsRevoked: 'ออกจากเซสชันที่ยืนยันตัวตนอื่นแล้ว', twoFactorDisabled: 'ปิดการยืนยันสองขั้นตอนแล้ว', profileTitle: 'โปรไฟล์', profileIntro: 'การเปลี่ยนอีเมลต้องยืนยันใหม่', timezone: 'เขตเวลา', saveProfile: 'บันทึกโปรไฟล์', emailVerification: 'การยืนยันอีเมล', verified: 'ยืนยันแล้ว', pending: 'รอดำเนินการ', twoFactorState: 'การยืนยันสองขั้นตอน', enabled: 'เปิดใช้งาน', setupPending: 'รอการตั้งค่า', notEnabled: 'ยังไม่เปิด', twoFactorTitle: 'การยืนยันสองขั้นตอน', twoFactorIntro: 'ปกป้องการเข้าสู่ระบบด้วยแอป TOTP รหัสกู้คืนจะแสดงเฉพาะตอนสร้างหรือสร้างใหม่', startSetup: 'เริ่มตั้งค่า', authenticatorSecret: 'รหัสลับของแอปยืนยันตัวตน', provisioningUri: 'URI การตั้งค่า', authenticationCode: 'รหัสยืนยันตัวตน', confirm: 'ยืนยัน', saveRecoveryCodes: 'บันทึกรหัสกู้คืนเหล่านี้ตอนนี้', recoveryIntro: 'แต่ละรหัสใช้ได้หนึ่งครั้ง เก็บไว้แยกจากบัญชีนี้', regenerateRecoveryCodes: 'สร้างรหัสกู้คืนใหม่', disableTwoFactor: 'ปิดการยืนยันสองขั้นตอน', passwordTitle: 'เปลี่ยนรหัสผ่าน', passwordIntro: 'การเปลี่ยนรหัสผ่านจะเพิกถอนโทเค็นการเข้าถึงส่วนบุคคลและเซสชันอื่น', currentPassword: 'รหัสผ่านปัจจุบัน', newPassword: 'รหัสผ่านใหม่', confirmNewPassword: 'ยืนยันรหัสผ่านใหม่', updatePassword: 'อัปเดตรหัสผ่าน', sessionsTitle: 'เซสชันอื่น', sessionsIntro: 'เพิกถอนทุกเซสชันที่ยืนยันตัวตนยกเว้นอุปกรณ์นี้', signOutOthers: 'ออกจากอุปกรณ์อื่น', dangerTitle: 'พื้นที่เสี่ยง', deleteAccount: 'ลบบัญชี',
  }, deletion: {
    eyebrow: 'วงจรบัญชี', title: 'ลบบัญชี', intro: 'การลบมีช่วงรอเจ็ดวัน การเป็นเจ้าของพันธมิตรที่ใช้งานอยู่ สิทธิ์ผู้ดูแลแพลตฟอร์ม และข้อกำหนดทางกฎหมายอาจขัดขวางการดำเนินการ บัญชีที่ประมวลผลจะถูกทำให้ไม่ระบุตัวตนโดยไม่ลบประวัติการตรวจสอบ', currentRequest: 'คำขอปัจจุบัน', status: 'สถานะ', eligibleAt: 'ดำเนินการได้เมื่อ', requestedAt: 'ขอเมื่อ', processedAt: 'ประมวลผลเมื่อ', notYet: 'ยังไม่', requestTitle: 'ขอลบบัญชี', requestIntro: 'โอนความเป็นเจ้าของพันธมิตรที่คุณถือครองก่อน ระเบียนที่อยู่ภายใต้ข้อกำหนดทางกฎหมายหรือจำเป็นต่อความปลอดภัยและการตรวจสอบจะถูกเก็บแบบนามแฝง', requestButton: 'ขอลบบัญชี', confirm: 'ต้องการขอลบบัญชีหรือไม่? มีช่วงรอเจ็ดวันและการตรวจสอบความเป็นเจ้าของ/ข้อกำหนดทางกฎหมาย', requested: 'บันทึกคำขอลบบัญชีแล้ว', backToAccount: 'กลับไปบัญชีและความปลอดภัย',
  } } },
  tr: { accountExperience: { account: {
    eyebrow: 'Hesap yönetimi', title: 'Hesap ve güvenlik', intro: 'Kimliğinizi, doğrulamayı, parolayı, iki faktörlü kimlik doğrulamayı ve etkin oturumları yönetin.', passwordUpdated: 'Parolanız güncellendi ve diğer doğrulanmış oturumlar iptal edildi.', sessionsRevoked: 'Diğer doğrulanmış oturumların oturumu kapatıldı.', twoFactorDisabled: 'İki faktörlü kimlik doğrulama devre dışı bırakıldı.', profileTitle: 'Profil', profileIntro: 'E-posta adresini değiştirmek yeniden doğrulama gerektirir.', timezone: 'Saat dilimi', saveProfile: 'Profili kaydet', emailVerification: 'E-posta doğrulaması', verified: 'Doğrulandı', pending: 'Bekliyor', twoFactorState: 'İki faktörlü kimlik doğrulama', enabled: 'Etkin', setupPending: 'Kurulum bekliyor', notEnabled: 'Etkin değil', twoFactorTitle: 'İki faktörlü kimlik doğrulama', twoFactorIntro: 'TOTP doğrulayıcı ile girişi koruyun. Kurtarma kodları yalnızca oluşturulduğunda veya yenilendiğinde gösterilir.', startSetup: 'Kurulumu başlat', authenticatorSecret: 'Doğrulayıcı gizli anahtarı', provisioningUri: 'Yapılandırma URI’si', authenticationCode: 'Doğrulama kodu', confirm: 'Onayla', saveRecoveryCodes: 'Bu kurtarma kodlarını şimdi kaydedin', recoveryIntro: 'Her kod bir kez çalışır. Bunları bu hesaptan ayrı bir yerde saklayın.', regenerateRecoveryCodes: 'Kurtarma kodlarını yenile', disableTwoFactor: 'İki faktörlü kimlik doğrulamayı kapat', passwordTitle: 'Parolayı değiştir', passwordIntro: 'Parolayı değiştirmek kişisel erişim belirteçlerini ve diğer doğrulanmış oturumları iptal eder.', currentPassword: 'Mevcut parola', newPassword: 'Yeni parola', confirmNewPassword: 'Yeni parolayı onayla', updatePassword: 'Parolayı güncelle', sessionsTitle: 'Diğer oturumlar', sessionsIntro: 'Bu cihaz dışında tüm doğrulanmış oturumları iptal edin.', signOutOthers: 'Diğer cihazlardan çıkış yap', dangerTitle: 'Tehlikeli alan', deleteAccount: 'Hesap silme',
  }, deletion: {
    eyebrow: 'Hesap yaşam döngüsü', title: 'Hesap silme', intro: 'Silme işleminde yedi günlük bekleme süresi vardır. Etkin ittifak sahipliği, platform yöneticisi erişimi ve yasal saklama işlemi engelleyebilir. İşlenen hesaplar denetim geçmişi silinmeden anonimleştirilir.', currentRequest: 'Mevcut istek', status: 'Durum', eligibleAt: 'Uygun tarih', requestedAt: 'İstek tarihi', processedAt: 'İşlendi', notYet: 'Henüz değil', requestTitle: 'Silme isteği', requestIntro: 'Önce sahip olduğunuz ittifakların sahipliğini devredin. Yasal saklama kapsamındaki veya güvenlik/denetim için gerekli kayıtlar takma adlı biçimde korunur.', requestButton: 'Hesap silme isteği', confirm: 'Hesap silme isteği gönderilsin mi? Yedi günlük bekleme süresi ile sahiplik/yasal saklama kontrolleri uygulanır.', requested: 'Hesap silme isteğiniz kaydedildi.', backToAccount: 'Hesap ve güvenliğe dön',
  } } },
  vi: { accountExperience: { account: {
    eyebrow: 'Quản lý tài khoản', title: 'Tài khoản & bảo mật', intro: 'Quản lý danh tính, xác minh, mật khẩu, xác thực hai yếu tố và các phiên đang hoạt động.', passwordUpdated: 'Mật khẩu đã được cập nhật và các phiên đã xác thực khác bị thu hồi.', sessionsRevoked: 'Các phiên đã xác thực khác đã đăng xuất.', twoFactorDisabled: 'Xác thực hai yếu tố đã bị tắt.', profileTitle: 'Hồ sơ', profileIntro: 'Thay đổi email yêu cầu xác minh lại.', timezone: 'Múi giờ', saveProfile: 'Lưu hồ sơ', emailVerification: 'Xác minh email', verified: 'Đã xác minh', pending: 'Đang chờ', twoFactorState: 'Xác thực hai yếu tố', enabled: 'Đã bật', setupPending: 'Đang chờ thiết lập', notEnabled: 'Chưa bật', twoFactorTitle: 'Xác thực hai yếu tố', twoFactorIntro: 'Bảo vệ đăng nhập bằng trình xác thực TOTP. Mã khôi phục chỉ hiển thị khi được tạo hoặc tạo lại.', startSetup: 'Bắt đầu thiết lập', authenticatorSecret: 'Mã bí mật xác thực', provisioningUri: 'URI cấp cấu hình', authenticationCode: 'Mã xác thực', confirm: 'Xác nhận', saveRecoveryCodes: 'Lưu các mã khôi phục này ngay', recoveryIntro: 'Mỗi mã chỉ dùng một lần. Hãy lưu chúng tách biệt khỏi tài khoản này.', regenerateRecoveryCodes: 'Tạo lại mã khôi phục', disableTwoFactor: 'Tắt xác thực hai yếu tố', passwordTitle: 'Đổi mật khẩu', passwordIntro: 'Đổi mật khẩu sẽ thu hồi token truy cập cá nhân và vô hiệu các phiên xác thực khác.', currentPassword: 'Mật khẩu hiện tại', newPassword: 'Mật khẩu mới', confirmNewPassword: 'Xác nhận mật khẩu mới', updatePassword: 'Cập nhật mật khẩu', sessionsTitle: 'Phiên khác', sessionsIntro: 'Thu hồi mọi phiên đã xác thực ngoại trừ thiết bị này.', signOutOthers: 'Đăng xuất thiết bị khác', dangerTitle: 'Khu vực nguy hiểm', deleteAccount: 'Xóa tài khoản',
  }, deletion: {
    eyebrow: 'Vòng đời tài khoản', title: 'Xóa tài khoản', intro: 'Việc xóa có thời gian chờ bảy ngày. Quyền sở hữu liên minh đang hoạt động, quyền quản trị nền tảng và yêu cầu lưu giữ pháp lý có thể chặn xử lý. Tài khoản đã xử lý được ẩn danh thay vì xóa lịch sử kiểm toán.', currentRequest: 'Yêu cầu hiện tại', status: 'Trạng thái', eligibleAt: 'Đủ điều kiện lúc', requestedAt: 'Yêu cầu lúc', processedAt: 'Xử lý lúc', notYet: 'Chưa', requestTitle: 'Yêu cầu xóa', requestIntro: 'Trước tiên hãy chuyển quyền sở hữu mọi liên minh. Hồ sơ thuộc diện lưu giữ pháp lý hoặc cần cho bảo mật/kiểm toán sẽ được giữ ở dạng giả danh.', requestButton: 'Yêu cầu xóa tài khoản', confirm: 'Yêu cầu xóa tài khoản? Có thời gian chờ bảy ngày và kiểm tra quyền sở hữu/lưu giữ pháp lý.', requested: 'Yêu cầu xóa tài khoản đã được ghi nhận.', backToAccount: 'Quay lại tài khoản & bảo mật',
  } } },
  'zh-CN': { accountExperience: { account: {
    eyebrow: '账户管理', title: '账户与安全', intro: '管理身份、邮箱验证、密码、双重验证和活动会话。', passwordUpdated: '密码已更新，其他已验证会话已撤销。', sessionsRevoked: '其他已验证会话已退出。', twoFactorDisabled: '双重验证已关闭。', profileTitle: '个人资料', profileIntro: '更改邮箱后需要重新验证。', timezone: '时区', saveProfile: '保存资料', emailVerification: '邮箱验证', verified: '已验证', pending: '待验证', twoFactorState: '双重验证', enabled: '已启用', setupPending: '设置待完成', notEnabled: '未启用', twoFactorTitle: '双重验证', twoFactorIntro: '使用 TOTP 验证器保护登录。恢复码只在创建或重新生成时显示。', startSetup: '开始设置', authenticatorSecret: '验证器密钥', provisioningUri: '配置 URI', authenticationCode: '验证码', confirm: '确认', saveRecoveryCodes: '立即保存这些恢复码', recoveryIntro: '每个恢复码只能使用一次，请与此账户分开保存。', regenerateRecoveryCodes: '重新生成恢复码', disableTwoFactor: '关闭双重验证', passwordTitle: '更改密码', passwordIntro: '更改密码会撤销个人访问令牌并使其他已验证会话失效。', currentPassword: '当前密码', newPassword: '新密码', confirmNewPassword: '确认新密码', updatePassword: '更新密码', sessionsTitle: '其他会话', sessionsIntro: '撤销除本设备以外的所有已验证会话。', signOutOthers: '退出其他设备', dangerTitle: '危险操作', deleteAccount: '删除账户',
  }, deletion: {
    eyebrow: '账户生命周期', title: '删除账户', intro: '删除账户有七天冷静期。当前联盟所有权、平台管理员权限和法律保留可能阻止处理。处理后的账户会匿名化，而不会静默删除审计历史。', currentRequest: '当前申请', status: '状态', eligibleAt: '可处理时间', requestedAt: '申请时间', processedAt: '处理时间', notYet: '尚未', requestTitle: '申请删除', requestIntro: '请先转移你拥有的所有联盟。受法律保留或安全、审计要求约束的记录会以假名化形式保留。', requestButton: '申请删除账户', confirm: '要申请删除账户吗？有七天冷静期，并会进行所有权和法律保留检查。', requested: '你的账户删除申请已记录。', backToAccount: '返回账户与安全',
  } } },
  'zh-TW': { accountExperience: { account: {
    eyebrow: '帳戶管理', title: '帳戶與安全', intro: '管理身分、電子郵件驗證、密碼、雙重驗證與目前工作階段。', passwordUpdated: '密碼已更新，其他已驗證工作階段已撤銷。', sessionsRevoked: '其他已驗證工作階段已登出。', twoFactorDisabled: '雙重驗證已停用。', profileTitle: '個人資料', profileIntro: '變更電子郵件後需要重新驗證。', timezone: '時區', saveProfile: '儲存資料', emailVerification: '電子郵件驗證', verified: '已驗證', pending: '待驗證', twoFactorState: '雙重驗證', enabled: '已啟用', setupPending: '設定待完成', notEnabled: '未啟用', twoFactorTitle: '雙重驗證', twoFactorIntro: '使用 TOTP 驗證器保護登入。復原碼只會在建立或重新產生時顯示。', startSetup: '開始設定', authenticatorSecret: '驗證器密鑰', provisioningUri: '設定 URI', authenticationCode: '驗證碼', confirm: '確認', saveRecoveryCodes: '立即儲存這些復原碼', recoveryIntro: '每個復原碼只能使用一次，請與此帳戶分開保存。', regenerateRecoveryCodes: '重新產生復原碼', disableTwoFactor: '停用雙重驗證', passwordTitle: '變更密碼', passwordIntro: '變更密碼會撤銷個人存取權杖並使其他已驗證工作階段失效。', currentPassword: '目前密碼', newPassword: '新密碼', confirmNewPassword: '確認新密碼', updatePassword: '更新密碼', sessionsTitle: '其他工作階段', sessionsIntro: '撤銷此裝置以外的所有已驗證工作階段。', signOutOthers: '登出其他裝置', dangerTitle: '危險操作', deleteAccount: '刪除帳戶',
  }, deletion: {
    eyebrow: '帳戶生命週期', title: '刪除帳戶', intro: '刪除帳戶有七天冷靜期。有效的聯盟所有權、平台管理員權限與法律保留可能阻止處理。已處理帳戶會匿名化，而不會移除稽核歷史。', currentRequest: '目前申請', status: '狀態', eligibleAt: '可處理時間', requestedAt: '申請時間', processedAt: '處理時間', notYet: '尚未', requestTitle: '申請刪除', requestIntro: '請先轉移你擁有的所有聯盟。受法律保留或安全、稽核要求約束的紀錄會以假名化形式保留。', requestButton: '申請刪除帳戶', confirm: '要申請刪除帳戶嗎？有七天冷靜期，並會進行所有權與法律保留檢查。', requested: '你的帳戶刪除申請已記錄。', backToAccount: '返回帳戶與安全',
  } } },
};
