import type { LocaleCode } from '../locales';

const base = {
  eyebrow: 'Kingdom diplomacy',
  diplomacyTitle: '{alliance} diplomacy',
  diplomacySubtitle: 'Explicit human-maintained relationship state for Kingdom {kingdom}. Observation changes and advisory dates never alter diplomacy automatically.',
  contacts: 'Diplomacy contacts', observationHistory: 'Observation history', trackingWorkspace: 'Tracking workspace',
  currentRelationship: 'Current relationship', state: 'State', effective: 'Effective', review: 'Review', expiry: 'Expiry', reviewStatus: 'Review status', reviewDue: 'Human review due', noReviewDue: 'No review due', lastChangedBy: 'Last changed by', noTransition: 'No explicit transition yet', terms: 'Terms', rationale: 'Rationale',
  recordState: 'Record explicit relationship state', recordStateHelp: 'Repeating the exact current state and metadata is idempotent. A material change appends a transition and preserves prior history.', readOnlyHistorical: 'This record is read-only because tracking is archived or belongs to historical Kingdom context. Existing history remains available.', relationshipState: 'Relationship state', effectiveTime: 'Effective time', reviewTime: 'Review time', reviewAdvisory: 'Advisory only; reaching this time never changes relationship state.', expiryTime: 'Expiry time', expiryAdvisory: 'Advisory only; expiry creates a review indicator.', privateTerms: 'Private terms', privateTermsHelp: 'Manager-private and excluded from shared event payloads.', privateRationale: 'Private rationale', privateRationaleHelp: 'Manager-private explanation for the explicit decision.', recordTransition: 'Record transition', transitionHistory: 'Transition history', transitionHistoryHelp: 'Append-oriented history preserves state, dates, private context, actor, and recorded time for each material change.', historyLimit: 'Up to {count} most recent transitions', transition: 'Transition', effectiveReview: 'Effective / review', privateContext: 'Private context', attribution: 'Attribution', noHistory: 'No diplomacy transitions have been recorded.', notSet: 'Not set',
  contactsEyebrow: 'Diplomacy coordination', contactsTitle: '{alliance} contacts', contactsSubtitle: 'Manager-private coordination handles for Kingdom {kingdom}. Contacts never create platform users, memberships, player identity, or permissions.', handlesSafety: 'Store coordination handles only. Do not store sensitive personal data or secrets in this directory.', contactReadOnly: 'This record is read-only because tracking is archived or belongs to historical Kingdom context. Existing contact history remains visible.', addContact: 'Add contact', editContact: 'Edit contact', contactHelp: 'Display names and handles are coordination labels only and never auto-link a Kingdom player or platform account.', displayName: 'Display name', gameRole: 'Game-side role/title', contactChannel: 'Contact channel', handle: 'Handle / identifier', lastVerified: 'Last verified', verificationHelp: 'Optional factual verification time; future values are rejected.', managerNotes: 'Private manager notes', saveContact: 'Save contact', cancelEdit: 'Cancel edit', directory: 'Private contact directory', directoryHelp: 'Inactive entries remain visible as coordination history and are not destructively deleted.', contactLimit: 'Up to {count} contacts', contact: 'Contact', channel: 'Channel', verification: 'Verification', lifecycle: 'Lifecycle', actions: 'Actions', noRole: 'No role recorded', noNotes: 'No private notes', updated: 'Updated {date}', deactivated: 'Deactivated {date} by {actor}', lastManager: 'Last manager {actor}', edit: 'Edit', deactivate: 'Deactivate', inactive: 'Inactive', noContacts: 'No diplomacy contacts have been recorded.', deactivateConfirm: 'Deactivate {name} as a diplomacy contact?',
  historyTitle: '{alliance} observation history', historySubtitle: 'Factual accepted observations for Kingdom {kingdom}. Recorded facts do not imply ranking or diplomacy state.', freshness: 'Freshness', latestPower: 'Latest power', latestMembers: 'Latest members', currentWithinDays: 'Current means captured within {days} days.', missingNotZero: 'Missing is distinct from zero.', captured: 'Captured {date}', recordObservation: 'Record observation', recordCorrection: 'Record correction', observationHelp: 'Exact retries are idempotent. Corrections append a new record and invalidate the original rather than rewriting history.', cancelCorrection: 'Cancel correction', observedName: 'Observed name', observedTag: 'Observed tag', power: 'Power', members: 'Members', capturedAt: 'Captured at', correctionReason: 'Correction reason', correctionPrivate: 'Manager-private correction context.', historicalObservations: 'Historical observations', historyHelp: 'Up to the latest 250 records are shown by capture time. Managers also see invalidated records and bounded provenance.', provenance: 'Provenance', correct: 'Correct', invalidate: 'Invalidate', invalidated: 'Invalidated', source: 'Source', unavailableActor: 'Unavailable actor', correctionOf: 'Correction of {id}', invalidatedBy: 'Invalidated by {actor} on {date}', invalidationReason: 'Invalidation reason', noObservations: 'No observations have been recorded.', invalidateReason: 'Reason for invalidation', confirmInvalidation: 'Confirm invalidation',
  intelligenceTitle: 'Alliance intelligence', intelligenceSubtitle: 'Descriptive operational comparisons from accepted observations and explicit diplomacy state. Missing values remain missing and no composite score is calculated.', activeTracked: 'Active tracked alliances', currentObservations: 'Current observations', staleMissing: 'Stale / missing observations', relationshipsReview: 'Relationships requiring review', diplomacyStates: 'Current diplomacy states', activeContact: 'Tracked alliances with an active contact', verificationDue: 'Tracked alliances with contact verification due', managerDiagnostic: 'Manager-private diagnostic only.', verificationDueHelp: 'Due means an active contact is unverified or older than {days} days.', filtersTitle: 'Filter and factual sorting', filtersHelp: 'Sorting changes navigation order only and does not create a best/worst ranking.', trackingState: 'Tracking state', observationFreshness: 'Observation freshness', diplomacyState: 'Diplomacy state', sortBy: 'Sort by', direction: 'Direction', apply: 'Apply', reset: 'Reset', all: 'All', active: 'Active', archived: 'Archived', current: 'Current', stale: 'Stale', missing: 'Missing', name: 'Name', tag: 'Tag', latestPowerSort: 'Latest power', latestMembersSort: 'Latest members', observationAge: 'Observation age', ascending: 'Ascending', descending: 'Descending', trendRules: 'How descriptive comparison windows work', trendRulesHelp: 'The current point is the latest accepted observation at or before the dashboard time. Prior change uses the immediately preceding accepted point. For an N-day comparison, the baseline is the closest accepted observation at or before the N-day target but no older than 2N days. Newer points are never substituted, older history outside the bounded window is ignored, and missing history is never interpolated.', windowsHelp: 'Current windows: {seven}–{sevenOldest} days and {thirty}–{thirtyOldest} days.', allianceIntelligence: 'Tracked alliance intelligence', latestFacts: 'Latest facts', priorChange: 'Prior change', sevenDay: '7-day change', thirtyDay: '30-day change', diplomacy: 'Diplomacy', contactsColumn: 'Contacts', insufficientHistory: 'Insufficient history', baseline: 'baseline {date}', daysOld: '{days} day(s) old', missingObservation: 'Missing observation', noRows: 'No tracked alliances match these filters.', asOf: 'As of {date}', manageTracking: 'Manage tracking', history: 'History', activeContacts: '{count} active', verificationDueShort: '{count} verification due', latestVerified: 'Latest verified {date}', noActiveContacts: 'No active contacts',
  unknown: 'Unknown', neutral: 'Neutral', friendly: 'Friendly', nap: 'NAP', ally: 'Ally', rival: 'Rival', inGame: 'In-game', discord: 'Discord', otherHandle: 'Other handle/channel',
} as const;

type Copy = { [K in keyof typeof base]: string };
type PartialCopy = Partial<Copy>;
const overrides: Partial<Record<LocaleCode, PartialCopy>> = {
  ar: { eyebrow: 'دبلوماسية المملكة', diplomacyTitle: 'دبلوماسية {alliance}', contacts: 'جهات الاتصال الدبلوماسية', observationHistory: 'سجل الملاحظات', currentRelationship: 'العلاقة الحالية', reviewDue: 'المراجعة البشرية مستحقة', recordTransition: 'تسجيل الانتقال', transitionHistory: 'سجل الانتقالات', contactsTitle: 'جهات اتصال {alliance}', addContact: 'إضافة جهة اتصال', editContact: 'تعديل جهة الاتصال', displayName: 'اسم العرض', lastVerified: 'آخر تحقق', historyTitle: 'سجل ملاحظات {alliance}', freshness: 'حداثة البيانات', latestPower: 'أحدث قوة', latestMembers: 'أحدث عدد أعضاء', recordObservation: 'تسجيل ملاحظة', recordCorrection: 'تسجيل تصحيح', historicalObservations: 'الملاحظات التاريخية', intelligenceTitle: 'استخبارات التحالف', activeTracked: 'التحالفات النشطة المتابعة', currentObservations: 'الملاحظات الحالية', diplomacyStates: 'حالات الدبلوماسية الحالية', filtersTitle: 'التصفية والترتيب الواقعي', apply: 'تطبيق', reset: 'إعادة ضبط', current: 'حالي', stale: 'قديم', missing: 'مفقود', active: 'نشط', archived: 'مؤرشف', all: 'الكل', history: 'السجل' },
  de: { eyebrow: 'Königreich-Diplomatie', diplomacyTitle: 'Diplomatie · {alliance}', contacts: 'Diplomatiekontakte', observationHistory: 'Beobachtungsverlauf', currentRelationship: 'Aktuelle Beziehung', reviewDue: 'Prüfung fällig', recordTransition: 'Übergang erfassen', transitionHistory: 'Übergangsverlauf', contactsTitle: 'Kontakte · {alliance}', addContact: 'Kontakt hinzufügen', editContact: 'Kontakt bearbeiten', displayName: 'Anzeigename', lastVerified: 'Zuletzt verifiziert', historyTitle: 'Beobachtungsverlauf · {alliance}', freshness: 'Aktualität', latestPower: 'Letzte Stärke', latestMembers: 'Letzte Mitgliederzahl', recordObservation: 'Beobachtung erfassen', recordCorrection: 'Korrektur erfassen', historicalObservations: 'Historische Beobachtungen', intelligenceTitle: 'Allianz-Intelligence', activeTracked: 'Aktiv verfolgte Allianzen', currentObservations: 'Aktuelle Beobachtungen', diplomacyStates: 'Aktuelle Diplomatiestatus', filtersTitle: 'Filter und faktische Sortierung', apply: 'Anwenden', reset: 'Zurücksetzen', current: 'Aktuell', stale: 'Veraltet', missing: 'Fehlend', active: 'Aktiv', archived: 'Archiviert', all: 'Alle', history: 'Verlauf' },
  es: { eyebrow: 'Diplomacia del reino', diplomacyTitle: 'Diplomacia de {alliance}', contacts: 'Contactos diplomáticos', observationHistory: 'Historial de observaciones', currentRelationship: 'Relación actual', reviewDue: 'Revisión pendiente', recordTransition: 'Registrar transición', transitionHistory: 'Historial de transiciones', contactsTitle: 'Contactos de {alliance}', addContact: 'Añadir contacto', editContact: 'Editar contacto', displayName: 'Nombre visible', lastVerified: 'Última verificación', historyTitle: 'Historial de observaciones de {alliance}', freshness: 'Actualidad', latestPower: 'Último poder', latestMembers: 'Últimos miembros', recordObservation: 'Registrar observación', recordCorrection: 'Registrar corrección', historicalObservations: 'Observaciones históricas', intelligenceTitle: 'Inteligencia de alianzas', activeTracked: 'Alianzas activas seguidas', currentObservations: 'Observaciones actuales', diplomacyStates: 'Estados diplomáticos actuales', filtersTitle: 'Filtros y orden factual', apply: 'Aplicar', reset: 'Restablecer', current: 'Actual', stale: 'Obsoleta', missing: 'Faltante', active: 'Activa', archived: 'Archivada', all: 'Todas', history: 'Historial' },
  fr: { eyebrow: 'Diplomatie du royaume', diplomacyTitle: 'Diplomatie · {alliance}', contacts: 'Contacts diplomatiques', observationHistory: 'Historique des observations', currentRelationship: 'Relation actuelle', reviewDue: 'Révision requise', recordTransition: 'Enregistrer la transition', transitionHistory: 'Historique des transitions', contactsTitle: 'Contacts · {alliance}', addContact: 'Ajouter un contact', editContact: 'Modifier le contact', displayName: 'Nom affiché', lastVerified: 'Dernière vérification', historyTitle: 'Historique des observations · {alliance}', freshness: 'Fraîcheur', latestPower: 'Puissance récente', latestMembers: 'Membres récents', recordObservation: 'Enregistrer une observation', recordCorrection: 'Enregistrer une correction', historicalObservations: 'Observations historiques', intelligenceTitle: 'Renseignement des alliances', activeTracked: 'Alliances actives suivies', currentObservations: 'Observations actuelles', diplomacyStates: 'États diplomatiques actuels', filtersTitle: 'Filtres et tri factuel', apply: 'Appliquer', reset: 'Réinitialiser', current: 'Actuel', stale: 'Périmé', missing: 'Manquant', active: 'Actif', archived: 'Archivé', all: 'Tous', history: 'Historique' },
  id: { eyebrow: 'Diplomasi kerajaan', diplomacyTitle: 'Diplomasi {alliance}', contacts: 'Kontak diplomasi', observationHistory: 'Riwayat observasi', currentRelationship: 'Hubungan saat ini', recordTransition: 'Catat transisi', contactsTitle: 'Kontak {alliance}', addContact: 'Tambah kontak', editContact: 'Edit kontak', historyTitle: 'Riwayat observasi {alliance}', intelligenceTitle: 'Intelijen aliansi', apply: 'Terapkan', reset: 'Atur ulang', current: 'Terkini', stale: 'Usang', missing: 'Hilang', active: 'Aktif', archived: 'Diarsipkan', all: 'Semua', history: 'Riwayat' },
  it: { eyebrow: 'Diplomazia del regno', diplomacyTitle: 'Diplomazia · {alliance}', contacts: 'Contatti diplomatici', observationHistory: 'Cronologia osservazioni', currentRelationship: 'Relazione attuale', recordTransition: 'Registra transizione', contactsTitle: 'Contatti · {alliance}', addContact: 'Aggiungi contatto', editContact: 'Modifica contatto', historyTitle: 'Cronologia osservazioni · {alliance}', intelligenceTitle: 'Intelligence alleanze', apply: 'Applica', reset: 'Reimposta', current: 'Corrente', stale: 'Obsoleto', missing: 'Mancante', active: 'Attivo', archived: 'Archiviato', all: 'Tutti', history: 'Cronologia' },
  ja: { eyebrow: '王国外交', diplomacyTitle: '{alliance} の外交', contacts: '外交連絡先', observationHistory: '観測履歴', currentRelationship: '現在の関係', recordTransition: '変更を記録', contactsTitle: '{alliance} の連絡先', addContact: '連絡先を追加', editContact: '連絡先を編集', historyTitle: '{alliance} の観測履歴', intelligenceTitle: '同盟インテリジェンス', apply: '適用', reset: 'リセット', current: '現在', stale: '古い', missing: '欠落', active: '有効', archived: 'アーカイブ', all: 'すべて', history: '履歴' },
  ko: { eyebrow: '왕국 외교', diplomacyTitle: '{alliance} 외교', contacts: '외교 연락처', observationHistory: '관측 기록', currentRelationship: '현재 관계', recordTransition: '전환 기록', contactsTitle: '{alliance} 연락처', addContact: '연락처 추가', editContact: '연락처 편집', historyTitle: '{alliance} 관측 기록', intelligenceTitle: '동맹 인텔리전스', apply: '적용', reset: '초기화', current: '현재', stale: '오래됨', missing: '누락', active: '활성', archived: '보관됨', all: '전체', history: '기록' },
  pl: { eyebrow: 'Dyplomacja królestwa', diplomacyTitle: 'Dyplomacja · {alliance}', contacts: 'Kontakty dyplomatyczne', observationHistory: 'Historia obserwacji', currentRelationship: 'Bieżąca relacja', recordTransition: 'Zapisz zmianę', contactsTitle: 'Kontakty · {alliance}', addContact: 'Dodaj kontakt', editContact: 'Edytuj kontakt', historyTitle: 'Historia obserwacji · {alliance}', intelligenceTitle: 'Analiza sojuszy', apply: 'Zastosuj', reset: 'Resetuj', current: 'Aktualne', stale: 'Nieaktualne', missing: 'Brak', active: 'Aktywne', archived: 'Zarchiwizowane', all: 'Wszystkie', history: 'Historia' },
  'pt-BR': { eyebrow: 'Diplomacia do reino', diplomacyTitle: 'Diplomacia de {alliance}', contacts: 'Contatos diplomáticos', observationHistory: 'Histórico de observações', currentRelationship: 'Relação atual', recordTransition: 'Registrar transição', contactsTitle: 'Contatos de {alliance}', addContact: 'Adicionar contato', editContact: 'Editar contato', historyTitle: 'Histórico de observações de {alliance}', intelligenceTitle: 'Inteligência de alianças', apply: 'Aplicar', reset: 'Redefinir', current: 'Atual', stale: 'Desatualizado', missing: 'Ausente', active: 'Ativo', archived: 'Arquivado', all: 'Todos', history: 'Histórico' },
  ru: { eyebrow: 'Дипломатия королевства', diplomacyTitle: 'Дипломатия · {alliance}', contacts: 'Дипломатические контакты', observationHistory: 'История наблюдений', currentRelationship: 'Текущие отношения', recordTransition: 'Записать переход', contactsTitle: 'Контакты · {alliance}', addContact: 'Добавить контакт', editContact: 'Изменить контакт', historyTitle: 'История наблюдений · {alliance}', intelligenceTitle: 'Аналитика альянсов', apply: 'Применить', reset: 'Сбросить', current: 'Текущее', stale: 'Устаревшее', missing: 'Отсутствует', active: 'Активно', archived: 'Архив', all: 'Все', history: 'История' },
  th: { eyebrow: 'การทูตของอาณาจักร', diplomacyTitle: 'การทูต · {alliance}', contacts: 'ผู้ติดต่อทางการทูต', observationHistory: 'ประวัติการสังเกต', currentRelationship: 'ความสัมพันธ์ปัจจุบัน', recordTransition: 'บันทึกการเปลี่ยน', contactsTitle: 'ผู้ติดต่อ · {alliance}', addContact: 'เพิ่มผู้ติดต่อ', editContact: 'แก้ไขผู้ติดต่อ', historyTitle: 'ประวัติการสังเกต · {alliance}', intelligenceTitle: 'ข้อมูลเชิงลึกพันธมิตร', apply: 'ใช้', reset: 'รีเซ็ต', current: 'ปัจจุบัน', stale: 'เก่า', missing: 'หายไป', active: 'ใช้งาน', archived: 'เก็บถาวร', all: 'ทั้งหมด', history: 'ประวัติ' },
  tr: { eyebrow: 'Krallık diplomasisi', diplomacyTitle: '{alliance} diplomasisi', contacts: 'Diplomasi kişileri', observationHistory: 'Gözlem geçmişi', currentRelationship: 'Mevcut ilişki', recordTransition: 'Geçişi kaydet', contactsTitle: '{alliance} kişileri', addContact: 'Kişi ekle', editContact: 'Kişiyi düzenle', historyTitle: '{alliance} gözlem geçmişi', intelligenceTitle: 'İttifak istihbaratı', apply: 'Uygula', reset: 'Sıfırla', current: 'Güncel', stale: 'Eski', missing: 'Eksik', active: 'Aktif', archived: 'Arşivli', all: 'Tümü', history: 'Geçmiş' },
  vi: { eyebrow: 'Ngoại giao vương quốc', diplomacyTitle: 'Ngoại giao · {alliance}', contacts: 'Liên hệ ngoại giao', observationHistory: 'Lịch sử quan sát', currentRelationship: 'Quan hệ hiện tại', recordTransition: 'Ghi chuyển trạng thái', contactsTitle: 'Liên hệ · {alliance}', addContact: 'Thêm liên hệ', editContact: 'Sửa liên hệ', historyTitle: 'Lịch sử quan sát · {alliance}', intelligenceTitle: 'Tình báo liên minh', apply: 'Áp dụng', reset: 'Đặt lại', current: 'Hiện tại', stale: 'Cũ', missing: 'Thiếu', active: 'Hoạt động', archived: 'Đã lưu trữ', all: 'Tất cả', history: 'Lịch sử' },
  'zh-CN': { eyebrow: '王国外交', diplomacyTitle: '{alliance} 外交', contacts: '外交联系人', observationHistory: '观测历史', currentRelationship: '当前关系', recordTransition: '记录变更', contactsTitle: '{alliance} 联系人', addContact: '添加联系人', editContact: '编辑联系人', historyTitle: '{alliance} 观测历史', intelligenceTitle: '联盟情报', apply: '应用', reset: '重置', current: '当前', stale: '过期', missing: '缺失', active: '活跃', archived: '已归档', all: '全部', history: '历史' },
  'zh-TW': { eyebrow: '王國外交', diplomacyTitle: '{alliance} 外交', contacts: '外交聯絡人', observationHistory: '觀測歷史', currentRelationship: '目前關係', recordTransition: '記錄變更', contactsTitle: '{alliance} 聯絡人', addContact: '新增聯絡人', editContact: '編輯聯絡人', historyTitle: '{alliance} 觀測歷史', intelligenceTitle: '聯盟情報', apply: '套用', reset: '重設', current: '目前', stale: '過期', missing: '缺失', active: '活躍', archived: '已封存', all: '全部', history: '歷史' },
};

export const kingdomP7BMessages = Object.fromEntries(
  (['en', 'ar', 'de', 'es', 'fr', 'id', 'it', 'ja', 'ko', 'pl', 'pt-BR', 'ru', 'th', 'tr', 'vi', 'zh-CN', 'zh-TW'] as LocaleCode[]).map((locale) => [locale, { kingdomP7B: { ...base, ...(overrides[locale] ?? {}) } }]),
) as Record<LocaleCode, { kingdomP7B: Copy }>;
