<?php

declare(strict_types=1);

return [
    'active_player_session_key' => 'game_world.active_player_id',
    'gift_code_redemption_url' => env('KINGSHOT_GIFT_CODE_URL', 'https://ks-giftcode.centurygame.com/'),
    'gift_codes' => [
        'moderation' => env('GIFT_CODES_MODERATION', false),
        'approved_source_ingestion' => env('GIFT_CODES_APPROVED_SOURCE_INGESTION', false),
        'notification_fanout' => env('GIFT_CODES_NOTIFICATION_FANOUT', false),
        'redemption_workspace' => env('GIFT_CODES_REDEMPTION_WORKSPACE', false),
        'redemption_intelligence' => env('GIFT_CODES_REDEMPTION_INTELLIGENCE', false),
        'alliance_coverage' => env('GIFT_CODES_ALLIANCE_COVERAGE', false),
        'contributor_reputation' => env('GIFT_CODES_CONTRIBUTOR_REPUTATION', false),
        'source_webhook_ingestion' => env('GIFT_CODES_SOURCE_WEBHOOK_INGESTION', false),
        'source_webhook_secret' => env('GIFT_CODES_SOURCE_WEBHOOK_SECRET'),
        'youtube_websub_secret' => env('GIFT_CODES_YOUTUBE_WEBSUB_SECRET'),
        'meta_app_secret' => env('GIFT_CODES_META_APP_SECRET'),
        'meta_webhook_verify_token' => env('GIFT_CODES_META_WEBHOOK_VERIFY_TOKEN'),
        'x_realtime_transport' => env('GIFT_CODES_X_REALTIME_TRANSPORT', false),
        'x_filtered_stream_webhook_entitled' => env('GIFT_CODES_X_FILTERED_STREAM_WEBHOOK_ENTITLED', false),
        'x_consumer_secret' => env('GIFT_CODES_X_CONSUMER_SECRET'),
        'discord_gateway_enabled' => env('GIFT_CODES_DISCORD_GATEWAY_ENABLED', false),
        'discord_gateway_intents' => (int) env('GIFT_CODES_DISCORD_GATEWAY_INTENTS', 33281),
        'push_payload_max_bytes' => (int) env('GIFT_CODES_PUSH_PAYLOAD_MAX_BYTES', 1000000),
        'source_stale_minutes' => (int) env('GIFT_CODES_SOURCE_STALE_MINUTES', 90),
        'source_smoke_check_max_age_hours' => (int) env('GIFT_CODES_SOURCE_SMOKE_CHECK_MAX_AGE_HOURS', 24),
        'quarantine_alert_consecutive_runs' => (int) env('GIFT_CODES_QUARANTINE_ALERT_CONSECUTIVE_RUNS', 3),
        'quota_alert_remaining' => (int) env('GIFT_CODES_QUOTA_ALERT_REMAINING', 10),
        'x_bearer_token' => env('GIFT_CODES_X_BEARER_TOKEN'),
        'discord_bot_token' => env('GIFT_CODES_DISCORD_BOT_TOKEN'),
        'youtube_api_key' => env('GIFT_CODES_YOUTUBE_API_KEY'),
        'reddit_client_id' => env('GIFT_CODES_REDDIT_CLIENT_ID'),
        'reddit_client_secret' => env('GIFT_CODES_REDDIT_CLIENT_SECRET'),
        'reddit_user_agent' => env('GIFT_CODES_REDDIT_USER_AGENT'),
        'facebook_access_token' => env('GIFT_CODES_FACEBOOK_ACCESS_TOKEN'),
        'instagram_access_token' => env('GIFT_CODES_INSTAGRAM_ACCESS_TOKEN'),
        'meta_graph_api_version' => env('GIFT_CODES_META_GRAPH_API_VERSION', 'v26.0'),
        'independent_evidence_threshold' => (int) env('GIFT_CODES_INDEPENDENT_EVIDENCE_THRESHOLD', 2),
        'max_redemption_attempts' => (int) env('GIFT_CODES_MAX_REDEMPTION_ATTEMPTS', 6),
        'fanout_batch_size' => (int) env('GIFT_CODES_FANOUT_BATCH_SIZE', 200),
        'catalog_page_size' => (int) env('GIFT_CODES_CATALOG_PAGE_SIZE', 25),
        'workspace_page_size' => (int) env('GIFT_CODES_WORKSPACE_PAGE_SIZE', 25),
        'max_session_codes' => (int) env('GIFT_CODES_MAX_SESSION_CODES', 100),
        'max_session_governors' => (int) env('GIFT_CODES_MAX_SESSION_GOVERNORS', 50),
        'max_session_items' => (int) env('GIFT_CODES_MAX_SESSION_ITEMS', 500),
        'intelligence_min_samples' => (int) env('GIFT_CODES_INTELLIGENCE_MIN_SAMPLES', 5),
        'intelligence_min_accounts' => (int) env('GIFT_CODES_INTELLIGENCE_MIN_ACCOUNTS', 5),
        'intelligence_window_hours' => (int) env('GIFT_CODES_INTELLIGENCE_WINDOW_HOURS', 168),
        'reminder_horizon_days' => (int) env('GIFT_CODES_REMINDER_HORIZON_DAYS', 30),
        'source_webhook_clock_skew_seconds' => (int) env('GIFT_CODES_SOURCE_WEBHOOK_CLOCK_SKEW_SECONDS', 300),
        'ingestion_batch_size' => (int) env('GIFT_CODES_INGESTION_BATCH_SIZE', 100),
        'ingestion_timeout_seconds' => (int) env('GIFT_CODES_INGESTION_TIMEOUT_SECONDS', 10),
        'ingestion_max_pages_per_source' => (int) env('GIFT_CODES_INGESTION_MAX_PAGES_PER_SOURCE', 3),
        'ingestion_retry_base_seconds' => (int) env('GIFT_CODES_INGESTION_RETRY_BASE_SECONDS', 60),
        'ingestion_retry_max_seconds' => (int) env('GIFT_CODES_INGESTION_RETRY_MAX_SECONDS', 3600),
        'transition_campaigns_per_run' => (int) env('GIFT_CODES_TRANSITION_CAMPAIGNS_PER_RUN', 10),
        'max_governors_per_account' => (int) env('GIFT_CODES_MAX_GOVERNORS_PER_ACCOUNT', 50),
    ],
];
