from pathlib import Path


tools_path = Path('resources/js/pages/Kingdom/Territory/Tools.vue')
text = tools_path.read_text()
replacements = [
    ("const { locale } = useLocale();", "const { locale, t } = useLocale();"),
    ('<Head :title="`${territory.plan.name} · Layout Tools`" />', '<Head :title="`${territory.plan.name} · ${t(\'territory.tools.title\')}`" />'),
    ('<p class="ks-kicker">Territory planning</p>', '<p class="ks-kicker">{{ t(\'territory.tools.eyebrow\') }}</p>'),
    ('<h1 class="ks-display text-3xl font-semibold">Layout Tools</h1>', '<h1 class="ks-display text-3xl font-semibold">{{ t(\'territory.tools.title\') }}</h1>'),
    ('{{ territory.plan.name }} · revision {{ revision }} · {{ status }}', "{{ territory.plan.name }} · {{ t('territory.revision', { revision }) }} · {{ t(`territory.status.${status}`) }}"),
    ('aria-label="Territory plan navigation"', ':aria-label="t(\'territory.tools.navigation\')"'),
    ('>Editor</Link>', ">{{ t('territory.editorTitle') }}</Link>"),
    ('>Plan vs observed</Link', ">{{ t('territory.reconciliationTitle') }}</Link"),
    ('>Plans</Link>', ">{{ t('territory.plansHeading') }}</Link>"),
    ('<p class="ks-kicker">Atomic editing</p>', '<p class="ks-kicker">{{ t(\'territory.tools.atomicEditing\') }}</p>'),
    ('Align, distribute and bulk coordinates', "{{ t('territory.tools.transformTitle') }}"),
    ('<span class="ks-chip">{{ selectedCount }} selected</span>', '<span class="ks-chip">{{ t(\'territory.selectedCount\', { count: selectedCount }) }}</span>'),
    ('>Select editable</AppButton>', ">{{ t('territory.tools.selectEditable') }}</AppButton>"),
    ('>Clear</AppButton>', ">{{ t('territory.tools.clear') }}</AppButton>"),
    ("['left', 'Align left'],", "['left', 'territory.tools.alignLeft'],"),
    ("['center_x', 'Center X'],", "['center_x', 'territory.tools.centerX'],"),
    ("['right', 'Align right'],", "['right', 'territory.tools.alignRight'],"),
    ("['top', 'Align top'],", "['top', 'territory.tools.alignTop'],"),
    ("['center_y', 'Center Y'],", "['center_y', 'territory.tools.centerY'],"),
    ("['bottom', 'Align bottom'],", "['bottom', 'territory.tools.alignBottom'],"),
    ('{{ item[1] }}', '{{ t(item[1]) }}'),
    ('            Distribute X\n', "            {{ t('territory.tools.distributeX') }}\n"),
    ('            Distribute Y\n', "            {{ t('territory.tools.distributeY') }}\n"),
    ('<th class="p-2">Select</th>', '<th class="p-2">{{ t(\'territory.select\') }}</th>'),
    ('<th class="p-2 text-start">Object</th>', '<th class="p-2 text-start">{{ t(\'territory.object\') }}</th>'),
    ('<th class="p-2 text-start">Layer</th>', '<th class="p-2 text-start">{{ t(\'territory.layer\') }}</th>'),
    ('<th class="p-2">X</th>', '<th class="p-2">{{ t(\'territory.explorer.xCoordinate\') }}</th>'),
    ('<th class="p-2">Y</th>', '<th class="p-2">{{ t(\'territory.explorer.yCoordinate\') }}</th>'),
    (':aria-label="`Select ${object.label ?? object.external_player_name ?? object.key}`"', ':aria-label="t(\'territory.tools.selectObject\', { object: object.label ?? object.external_player_name ?? object.key })"'),
    ('>Save layout</AppButton', ">{{ t('territory.save') }}</AppButton"),
    ('>Unsaved layout changes</span>', ">{{ t('territory.tools.unsavedChanges') }}</span>"),
    ('<p class="ks-kicker">Interchange</p>', '<p class="ks-kicker">{{ t(\'territory.tools.interchange\') }}</p>'),
    ('<h2 id="csv-heading" class="ks-display text-xl font-semibold">CSV coordinate table</h2>', '<h2 id="csv-heading" class="ks-display text-xl font-semibold">{{ t(\'territory.tools.csvTitle\') }}</h2>'),
    ('          Preview is strict and bounded; applying coordinates is one atomic command and respects\n          locks.\n', "          {{ t('territory.tools.csvHelp') }}\n"),
    ('>Export CSV</a', ">{{ t('territory.tools.exportCsv') }}</a"),
    ('          >CSV preview\n', "          >{{ t('territory.tools.csvPreview') }}\n"),
    ('placeholder="key,type,variant_key,x,y,rotation,..."', ':placeholder="t(\'territory.tools.csvPlaceholder\')"'),
    ('>Validate CSV</AppButton', ">{{ t('territory.tools.validateCsv') }}</AppButton"),
    ('>Apply coordinates</AppButton', ">{{ t('territory.tools.applyCoordinates') }}</AppButton"),
    ('          {{ coordinatePreview.length }} validated row(s) ready to apply.\n', "          {{ t('territory.tools.validatedRows', { count: coordinatePreview.length }) }}\n"),
    ('<p class="ks-kicker">Annotations</p>', '<p class="ks-kicker">{{ t(\'territory.tools.annotations\') }}</p>'),
    ('              Plan annotations\n', "              {{ t('territory.tools.planAnnotations') }}\n"),
    ('>Add annotation</AppButton', ">{{ t('territory.tools.addAnnotation') }}</AppButton"),
    ('<legend class="px-1 text-xs font-semibold">Annotation {{ index + 1 }}</legend>', '<legend class="px-1 text-xs font-semibold">{{ t(\'territory.tools.annotationNumber\', { number: index + 1 }) }}</legend>'),
    ('                >Kind<select', "                >{{ t('territory.tools.kind') }}<select"),
    ('<option value="label">Label</option>', '<option value="label">{{ t(\'territory.tools.label\') }}</option>'),
    ('<option value="line">Line</option>', '<option value="line">{{ t(\'territory.tools.line\') }}</option>'),
    ('<option value="arrow">Arrow</option>', '<option value="arrow">{{ t(\'territory.tools.arrow\') }}</option>'),
    ('<option value="rectangle">Rectangle</option>', '<option value="rectangle">{{ t(\'territory.tools.rectangle\') }}</option>'),
    ('                >Alliance<select', "                >{{ t('territory.alliance') }}<select"),
    ('<option :value="null">All layers</option>', '<option :value="null">{{ t(\'territory.tools.allLayers\') }}</option>'),
    ('                >Target X<input', "                >{{ t('territory.tools.targetX') }}<input"),
    ('                >Target Y<input', "                >{{ t('territory.tools.targetY') }}<input"),
    ('                >Text<input', "                >{{ t('territory.tools.text') }}<input"),
    ('              Remove\n', "              {{ t('territory.tools.remove') }}\n"),
    ('>Save annotations</AppButton', ">{{ t('territory.tools.saveAnnotations') }}</AppButton"),
    ('<p class="ks-kicker">Hive Builder</p>', '<p class="ks-kicker">{{ t(\'territory.hiveBuilder\') }}</p>'),
    ('          Reusable Hive templates\n', "          {{ t('territory.tools.reusableHiveTemplates') }}\n"),
    ('            >Template name<input', "            >{{ t('territory.tools.templateName') }}<input"),
    ('            >Style<select', "            >{{ t('territory.tools.style') }}<select"),
    ('<option value="swirl">Swirl</option>', '<option value="swirl">{{ t(\'territory.tools.swirl\') }}</option>'),
    ('<option value="banner_pad">Banner pad</option>', '<option value="banner_pad">{{ t(\'territory.tools.bannerPad\') }}</option>'),
    ('            >City count<input', "            >{{ t('territory.cityCount') }}<input"),
    ('            >Spacing<input', "            >{{ t('territory.tools.spacing') }}<input"),
    ('>Save template</AppButton', ">{{ t('territory.tools.saveTemplate') }}</AppButton"),
    ('            >Saved template<select', "            >{{ t('territory.tools.savedTemplate') }}<select"),
    ('<option value="">Choose template</option>', '<option value="">{{ t(\'territory.tools.chooseTemplate\') }}</option>'),
    ('{{ template.name }} · {{ template.style }} · {{ template.city_count }} cities', "{{ template.name }} · {{ template.style }} · {{ t('territory.tools.cities', { count: template.city_count }) }}"),
    ('              >Alliance<select', "              >{{ t('territory.alliance') }}<select"),
    ('              >Center X<input', "              >{{ t('territory.tools.centerX') }}<input"),
    ('              >Center Y<input', "              >{{ t('territory.tools.centerY') }}<input"),
    ('>Instantiate template</AppButton', ">{{ t('territory.tools.instantiateTemplate') }}</AppButton"),
    ('<p class="ks-kicker">Visual evidence</p>', '<p class="ks-kicker">{{ t(\'territory.tools.visualEvidence\') }}</p>'),
    ('              Persisted renditions\n', "              {{ t('territory.tools.persistedRenditions') }}\n"),
    ('>Persist artwork SVG</AppButton', ">{{ t('territory.tools.persistArtworkSvg') }}</AppButton"),
    ('          Persistence is revision-pinned and fails closed until real authorized artwork bytes can be\n          embedded.\n', "          {{ t('territory.tools.renditionHelp') }}\n"),
    ('<th class="p-2 text-start">Created</th>', '<th class="p-2 text-start">{{ t(\'territory.tools.created\') }}</th>'),
    ('<th class="p-2 text-start">Revision</th>', '<th class="p-2 text-start">{{ t(\'territory.tools.revision\') }}</th>'),
    ('<th class="p-2 text-start">Scope</th>', '<th class="p-2 text-start">{{ t(\'territory.scope\') }}</th>'),
    ('<th class="p-2 text-start">Type</th>', '<th class="p-2 text-start">{{ t(\'territory.tools.type\') }}</th>'),
    ('<th class="p-2 text-start">Checksum</th>', '<th class="p-2 text-start">{{ t(\'territory.tools.checksum\') }}</th>'),
    ('<th class="p-2">Action</th>', '<th class="p-2">{{ t(\'territory.tools.action\') }}</th>'),
    ('                    Reopen\n', "                    {{ t('territory.tools.reopen') }}\n"),
]
for old, new in replacements:
    if old not in text:
        raise SystemExit(f'Tools localization target not found: {old[:80]!r}')
    text = text.replace(old, new, 1)
tools_path.write_text(text)

index_path = Path('resources/js/pages/Kingdom/Territory/Index.vue')
index = index_path.read_text()
old = '                Layout tools\n'
if old not in index:
    raise SystemExit('Index Layout tools target not found')
index_path.write_text(index.replace(old, "                {{ t('territory.tools.title') }}\n", 1))

block = """    tools: {
      title: 'Layout Tools',
      eyebrow: 'Territory planning',
      navigation: 'Territory plan navigation',
      atomicEditing: 'Atomic editing',
      transformTitle: 'Align, distribute and bulk coordinates',
      selectEditable: 'Select editable',
      clear: 'Clear',
      alignLeft: 'Align left',
      centerX: 'Center X',
      alignRight: 'Align right',
      alignTop: 'Align top',
      centerY: 'Center Y',
      alignBottom: 'Align bottom',
      distributeX: 'Distribute X',
      distributeY: 'Distribute Y',
      selectObject: 'Select {object}',
      unsavedChanges: 'Unsaved layout changes',
      interchange: 'Interchange',
      csvTitle: 'CSV coordinate table',
      csvHelp: 'Preview is strict and bounded; applying coordinates is one atomic command and respects locks.',
      exportCsv: 'Export CSV',
      csvPreview: 'CSV preview',
      csvPlaceholder: 'key,type,variant_key,x,y,rotation,...',
      validateCsv: 'Validate CSV',
      applyCoordinates: 'Apply coordinates',
      validatedRows: '{count} validated row(s) ready to apply.',
      annotations: 'Annotations',
      planAnnotations: 'Plan annotations',
      addAnnotation: 'Add annotation',
      annotationNumber: 'Annotation {number}',
      kind: 'Kind',
      label: 'Label',
      line: 'Line',
      arrow: 'Arrow',
      rectangle: 'Rectangle',
      allLayers: 'All layers',
      targetX: 'Target X',
      targetY: 'Target Y',
      text: 'Text',
      remove: 'Remove',
      saveAnnotations: 'Save annotations',
      reusableHiveTemplates: 'Reusable Hive templates',
      templateName: 'Template name',
      style: 'Style',
      swirl: 'Swirl',
      bannerPad: 'Banner pad',
      spacing: 'Spacing',
      saveTemplate: 'Save template',
      savedTemplate: 'Saved template',
      chooseTemplate: 'Choose template',
      cities: '{count} cities',
      instantiateTemplate: 'Instantiate template',
      visualEvidence: 'Visual evidence',
      persistedRenditions: 'Persisted renditions',
      persistArtworkSvg: 'Persist artwork SVG',
      renditionHelp: 'Persistence is revision-pinned and fails closed until real authorized artwork bytes can be embedded.',
      created: 'Created',
      revision: 'Revision',
      type: 'Type',
      checksum: 'Checksum',
      action: 'Action',
      reopen: 'Reopen',
    },
"""
for catalogue in Path('resources/js/localization/messages/territory').glob('*.ts'):
    source = catalogue.read_text()
    if '    tools: {' in source:
        continue
    marker = '    eyebrow:'
    if marker not in source:
        raise SystemExit(f'catalogue marker missing: {catalogue}')
    catalogue.write_text(source.replace(marker, block + marker, 1))
