import type { MessageCatalogue } from './types';

const english: MessageCatalogue = {
  receipts: {
    'alliance-settings-updated': 'Alliance settings updated.',
    'alliance-role-created': 'Specialist role created.',
    'alliance-role-updated': 'Specialist role updated.',
    'alliance-role-archived': 'Specialist role archived.',
    'alliance-bulk-rank-completed':
      '{succeeded} ranks updated. {failed} need review. {skipped} were already up to date.',
    'alliance-bulk-role-completed':
      '{succeeded} role assignments updated. {failed} need review. {skipped} were already up to date.',
    'alliance-roster-evidence-uploaded': 'Alliance roster screenshot uploaded.',
    'alliance-roster-evidence-duplicate': 'This Alliance roster screenshot was already uploaded.',
    'alliance-roster-evidence-reviewed': 'Alliance roster screenshot review saved.',
    'alliance-roster-evidence-committed': '{count} reviewed roster observations committed.',
    'recruitment-reentry-updated': 'Recruitment re-entry control updated.',
    'notification-preference-reset': 'Governor notification preference reset to the account default.',
    'notification-marked-unread': 'Notification marked as unread.',
    'notification-archived': 'Notification archived.',
    'notification-restored': 'Notification restored.',
  },
  application: {
    dashboard: {
      commandReasons: {
        rosterReconciliationRequired: '{count} roster observations need officer reconciliation',
        recruitmentReentryReviewDue: '{count} recruitment re-entry reviews are due',
      },
      commandOwners: {
        alliance: {
          recruitment: 'Recruitment',
        },
      },
    },
  },
  allianceExpansion: {
    navSettings: 'Alliance settings',
    navRoles: 'Specialist roles',
    navBulk: 'Bulk administration',
    navHistory: 'Governance history',
    navRosterEvidence: 'Roster screenshots',
    navReconciliation: 'Roster reconciliation',
    settingsEyebrow: 'Alliance administration',
    settingsTitle: 'Alliance settings',
    settingsSubtitle:
      'Manage application-owned Alliance identity and defaults. Platform lifecycle and Kingdom ownership remain outside this surface.',
    allianceName: 'Alliance name',
    allianceUrlName: 'Alliance URL name',
    language: 'Default language',
    timezone: 'Time zone',
    saveSettings: 'Save Alliance settings',
    rolesEyebrow: 'Delegated responsibility',
    rolesTitle: 'Specialist roles',
    rolesSubtitle:
      'Create Alliance-scoped specialist roles from the existing permission vocabulary. R1–R5 leadership remains separate.',
    createRole: 'Create specialist role',
    roleName: 'Role name',
    permissions: 'Permissions',
    memberCount: '{count} members',
    systemRole: 'System role',
    customRole: 'Custom role',
    archivedRole: 'Archived',
    activeRole: 'Active',
    updateRole: 'Update role',
    archiveRole: 'Archive role',
    archiveRoleHelp:
      'Archived roles cannot be assigned again. Existing assignments remain visible until explicitly removed.',
    noRoles: 'No specialist roles are available.',
    permissionLabels: {
      'alliance.view': 'View Alliance',
      'alliance.manage': 'Manage Alliance settings',
      'membership.manage': 'Manage membership',
      'roles.manage': 'Manage ranks and specialist roles',
      'invitations.manage': 'Manage invitations',
      'content.manage': 'Manage Alliance content',
      'recruitment.manage': 'Manage recruitment',
    },
    bulkEyebrow: 'Bounded officer changes',
    bulkTitle: 'Bulk member administration',
    bulkSubtitle:
      'Preview up to 50 explicit members, then commit through the same owner actions used for single-member changes.',
    selectedMembers: '{count} selected',
    selectAll: 'Select all shown',
    clearSelection: 'Clear selection',
    rankChange: 'Rank change',
    targetRank: 'Target rank',
    previewRank: 'Preview rank changes',
    commitRank: 'Commit rank changes',
    roleChange: 'Specialist role change',
    targetRole: 'Specialist role',
    assignRole: 'Assign role',
    removeRole: 'Remove role',
    previewRole: 'Preview role changes',
    commitRole: 'Commit role changes',
    previewTitle: 'Preview',
    resultTitle: 'Latest result',
    outcomeSucceeded: 'Succeeded',
    outcomeFailed: 'Failed',
    outcomeSkipped: 'Skipped',
    noPreview: 'Preview a bounded change before committing it.',
    historyEyebrow: 'Factual audit history',
    historyTitle: 'Alliance governance history',
    historySubtitle:
      'Read-only history composed from owner audit events. It records what changed without creating a second source of truth.',
    capability: 'Capability',
    actorPlayerId: 'Actor Governor ID',
    applyFilters: 'Apply filters',
    clearFilters: 'Clear filters',
    occurredAt: 'Occurred',
    actor: 'Actor',
    event: 'Event',
    source: 'Source',
    details: 'Details',
    openOwner: 'Open owner workflow',
    loadOlder: 'Load older events',
    noHistory: 'No governance events match these filters.',
    memberHistoryEyebrow: 'Member governance evidence',
    memberHistoryTitle: '{name} history',
    memberHistorySubtitle:
      'Membership, rank, role and leadership facts recorded for this Governor in the current Alliance.',
    gamePlayerId: 'Game Player ID',
    rosterEvidenceEyebrow: 'Human-reviewed evidence',
    rosterEvidenceTitle: 'Alliance roster screenshots',
    rosterEvidenceSubtitle:
      'Upload a private roster screenshot, review every visible Governor row, state whether the roster is complete, then commit observations. Membership is never changed automatically.',
    screenshotFile: 'Roster screenshot',
    uploadScreenshot: 'Upload screenshot',
    recentEvidence: 'Recent screenshot evidence',
    evidenceStatus: 'Status',
    uploadedAt: 'Uploaded',
    exactDuplicate: 'Exact duplicate',
    visualDuplicate: 'Possible visual duplicate',
    noEvidence: 'No Alliance roster screenshots have been uploaded.',
    capturedAt: 'Captured at',
    completeRoster: 'This screenshot shows the complete Alliance roster',
    completeRosterHelp:
      'Only a reviewer-confirmed complete roster can support a missing-member observation. Partial screenshots never imply a member left.',
    allowSemanticDuplicate: 'Accept equivalent reviewed facts as a deliberate duplicate',
    observedRows: 'Reviewed Governor rows',
    observedName: 'Observed name',
    observedRank: 'Observed rank',
    power: 'Power',
    rosterEntry: 'Linked roster entry',
    noLinkedRosterEntry: 'No linked roster entry',
    addRow: 'Add row',
    removeRow: 'Remove row',
    saveReview: 'Save reviewed rows',
    commitReview: 'Commit observations',
    reconciliationEyebrow: 'Observed reality vs membership',
    reconciliationTitle: 'Alliance roster reconciliation',
    reconciliationSubtitle:
      'Compare the latest accepted roster observation with current Membership and Roster facts. Resolve differences through the owning workflows.',
    latestBatch: 'Latest accepted roster batch',
    noBatch: 'No accepted Alliance roster observation is available yet.',
    completeObservation: 'Complete roster observation',
    partialObservation: 'Partial roster observation',
    matched: '{count} matched',
    needsReview: '{count} need review',
    identityState: 'Identity match',
    reasons: 'Reasons',
    currentMembershipAction: 'Review membership',
    reconciliationReasons: {
      matches_membership: 'Matches current membership',
      ambiguous_identity: 'Identity is ambiguous',
      observation_without_membership: 'Observed Governor has no active membership',
      observed_new: 'New observed Governor',
      name_changed: 'Observed name differs',
      rank_changed: 'Observed rank differs',
      power_changed: 'Observed power differs from the latest baseline',
      membership_without_observation: 'Active member was not observed',
      observed_missing: 'Missing from reviewer-confirmed complete roster',
    },
    identityStates: {
      linked: 'Linked roster entry',
      game_id: 'Matched by Game Player ID',
      name: 'Matched by unique name',
      ambiguous: 'Ambiguous name match',
      unmatched: 'Unmatched observation',
      membership_only: 'Membership only',
    },
    recruitmentEyebrow: 'Alliance-local recruiting control',
    recruitmentTitle: 'Recruitment re-entry control',
    recruitmentSubtitle:
      'Set a private Alliance-local recruiting restriction. This is not a cross-Alliance or platform blacklist.',
    candidate: 'Candidate',
    currentStage: 'Current stage',
    reentryControl: 'Re-entry control',
    reason: 'Private reason',
    reviewAt: 'Review or reapply date',
    blocking: 'Currently blocks conversion',
    notBlocking: 'Does not block conversion',
    saveReentry: 'Save re-entry control',
    reentryControls: {
      normal: 'Normal',
      do_not_invite: 'Do not invite',
      reapply_after: 'Reapply after date',
      review_required: 'Officer review required',
    },
  },
};

export function allianceCapabilityExpansionLabels(): MessageCatalogue {
  return english;
}
