import type { MessageCatalogue } from './types';

const english: MessageCatalogue = {
  notifications: {
    eyebrow: 'Recipient delivery',
    title: 'Notifications',
    subtitle:
      'Read each notification once, then choose how and when Kingshot Alliance may deliver it to your account and active Governor.',
    unread: 'Unread',
    externalChannels: 'Destinations',
    needsAttention: 'Delivery issues',
    latestActivity: 'Notification Center 2.0',
    inbox: 'Inbox',
    inboxCount: '{count} messages shown',
    filters: 'Filters',
    applyFilters: 'Apply filters',
    clearFilters: 'Clear filters',
    view: 'View',
    type: 'Notification type',
    scope: 'Scope',
    deliveryStatus: 'Delivery status',
    dateFrom: 'From date',
    dateTo: 'To date',
    allTypes: 'All notification types',
    allStatuses: 'All delivery statuses',
    views: {
      all: 'Active',
      unread: 'Unread',
      archived: 'Archived',
    },
    scopes: {
      all: 'Account + active Governor',
      account: 'Account only',
      governor: 'Active Governor only',
    },
    scopeAccount: 'Account',
    scopeGovernor: 'Governor',
    urgency: 'Urgency',
    deliveryDetails: 'Delivery details',
    deliveryRoutes: '{count} delivery routes',
    noDeliveryRoutes: 'No external routes were selected for this message.',
    destination: 'Destination',
    attempts: '{attempts} of {max} attempts',
    retryAt: 'Next retry {date}',
    routingReason: 'Routing: {reason}',
    dueAt: 'Due {date}',
    sentAt: 'Sent {date}',
    failedAt: 'Failed {date}',
    open: 'Open',
    markRead: 'Mark read',
    markUnread: 'Mark unread',
    archive: 'Archive',
    restore: 'Restore',
    empty: 'No notifications match these filters.',
    loadMore: 'Load older messages',
    endOfInbox: 'No older messages match these filters.',
    deliverySetup: 'Delivery setup',
    deliveryChannels: 'Named destinations',
    deliverySecurity:
      'External credentials are encrypted and never returned to the browser. Each destination is scoped to the active Governor.',
    destinationHealth: 'Health',
    healthStatuses: {
      never_tested: 'Never tested',
      healthy: 'Healthy',
      degraded: 'Failing',
      paused: 'Paused',
    },
    lastVerified: 'Last verified {date}',
    lastSuccessfulDelivery: 'Last successful delivery {date}',
    lastFailedDelivery: 'Last failed delivery {date}',
    consecutiveFailures: '{count} consecutive failures',
    pause: 'Pause',
    resume: 'Resume',
    test: 'Test',
    reverify: 'Reverify',
    remove: 'Remove',
    label: 'Destination name',
    webhookUrl: 'Discord webhook URL',
    botToken: 'Telegram bot token',
    chatId: 'Telegram chat ID',
    saveChannel: 'Add {channel} destination',
    selectGovernor: 'Select a Governor to manage external destinations.',
    webPushSetup: 'Browser notifications',
    webPushHelp:
      'Enable this browser as a named Web Push destination. Each browser or installed app is stored separately.',
    webPushUnavailable:
      'Web Push is not available in this browser or is not configured on the server.',
    webPushDenied: 'Browser notification permission was denied.',
    webPushLabel: 'This device',
    enableWebPush: 'Enable Web Push on this device',
    enablingWebPush: 'Enabling Web Push…',
    webPushFailed: 'Web Push could not be enabled on this device.',
    preferences: 'Preferences',
    reminderRouting: 'Account defaults and Governor overrides',
    preferenceHelp:
      'Account defaults apply everywhere. An active-Governor override wins only for that Governor and can be reset to inherit the account default.',
    accountDefaults: 'Account defaults',
    governorOverrides: 'Active Governor overrides',
    inherited: 'Inherited',
    enabled: 'Enabled',
    disabled: 'Disabled',
    resetOverride: 'Reset override',
    emailOptIn: 'Email is opt-in and uses the verified account email owned by Accounts.',
    routingPolicy: 'Delivery timing policy',
    routingPolicyHelp:
      'These controls change when permitted external routes deliver. They never change whether a source-domain notification exists.',
    policyScope: 'Policy scope',
    timezone: 'Time zone',
    quietHours: 'Enable quiet hours',
    quietHoursStart: 'Quiet hours start',
    quietHoursEnd: 'Quiet hours end',
    allowUrgentDuringQuietHours: 'Allow urgent notifications during quiet hours',
    mutedUntil: 'Mute external delivery until',
    digestCadence: 'External delivery cadence',
    dailyDigestTime: 'Daily digest time',
    digestUrgent: 'Include urgent notifications in digests',
    savePolicy: 'Save routing policy',
    resetPolicy: 'Reset Governor policy',
    policyInherited: 'This Governor currently inherits the account routing policy.',
    cadences: {
      immediate: 'Immediate',
      hourly: 'Hourly digest',
      daily: 'Daily digest',
    },
    channels: {
      in_app: 'In app',
      discord: 'Discord',
      telegram: 'Telegram',
      web_push: 'Web Push',
      email: 'Email',
    },
    statuses: {
      queued: 'Queued',
      pending: 'Sending',
      sent: 'Sent',
      failed: 'Failed',
      cancelled: 'Cancelled',
    },
    types: {
      accountSecurity: 'Account security',
      allianceAnnouncement: 'Alliance announcement',
      eventReminder: 'Event reminder',
      giftCodeExpiring: 'Gift Code expiring',
      giftCodeAvailable: 'Gift Code available',
      giftCodeTrustChanged: 'Gift Code trust changed',
      giftCodeReminder: 'Gift Code reminder',
      giftCodeRedemptionReady: 'Gift Codes ready to redeem',
      intelligenceChange: 'Intelligence change',
      kingPerkReminder: 'King Perk reminder',
      officerBrief: 'Officer brief',
    },
    bulk: {
      selected: '{count} messages selected',
      help: 'Preview up to 50 concrete logical messages before applying an inbox change.',
      operation: 'Bulk operation',
      markRead: 'Mark read',
      markUnread: 'Mark unread',
      archive: 'Archive',
      restore: 'Restore',
      selectVisible: 'Select shown',
      clearSelection: 'Clear selection',
      selectNotification: 'Select {title}',
      preview: 'Preview',
      previewing: 'Previewing…',
      previewTitle: 'Bulk action preview',
      previewSummary: '{ready} ready; {blocked} blocked or already current.',
      confirm: 'Apply changes',
      confirmTitle: 'Apply inbox changes?',
      confirmDescription: 'Apply {operation} to {count} reviewed messages.',
      applying: 'Applying…',
      resultTitle: 'Latest bulk result',
      resultSummary: '{succeeded} succeeded; {failed} failed; {skipped} skipped.',
      failedSelected: 'Failed items remain selected so they can be reviewed or retried.',
      operationLabels: {
        mark_read: 'mark read',
        mark_unread: 'mark unread',
        archive: 'archive',
        restore: 'restore',
      },
      outcomes: {
        ready: 'Ready',
        'notification-unavailable': 'Unavailable',
        'already-read': 'Already read',
        'already-unread': 'Already unread',
        'already-archived': 'Already archived',
        'already-restored': 'Already restored',
        'notification-marked-read': 'Marked read',
        'notification-marked-unread': 'Marked unread',
        'notification-archived': 'Archived',
        'notification-restored': 'Restored',
        'notification-operation-unsupported': 'Unsupported',
      },
    },
  },
};

export function communicationsRecipientDeliveryLabels(): MessageCatalogue {
  return english;
}
