import type { MessageCatalogue } from './types';

const english: MessageCatalogue = {
  giftCodes: {
    workspace: {
      eyebrow: 'Redemption workspace',
      title: 'Gift Code Workspace',
      subtitle: 'Work through every currently eligible Gift Code across your owned Governors.',
      openWorkspace: 'Open redemption workspace',
      backToCatalogue: 'Back to catalogue',
      views: {
        new: 'New',
        ready: 'Ready to redeem',
        expiring: 'Expiring soon',
        retry_ready: 'Retry ready',
        in_progress: 'In progress',
        snoozed: 'Snoozed',
        completed: 'Completed',
      },
      shownCodes: '{count} codes shown',
      sourceCount: '{count} source records',
      expires: 'Expires {date}',
      noExpiry: 'No qualified expiry',
      noCodes: 'No Gift Codes match this workspace view.',
      selectCode: 'Select {code}',
      selectGovernor: 'Select {governor}',
      personalActions: 'Personal actions',
      pin: 'Pin',
      restore: 'Restore',
      snoozeDay: 'Snooze 24 hours',
      dismiss: 'Dismiss',
      remindDay: 'Remind me in 24 hours',
      createRun: 'Start redemption run',
      runModes: {
        all_actionable: 'Redeem all ready',
        expiring: 'Redeem expiring',
        retry_ready: 'Retry due items',
        selected: 'Redeem selected',
      },
      selectedSummary: '{codes} codes · {governors} Governors selected',
      currentRun: 'Current redemption run',
      runProgress: '{completed} of {total} completed',
      runFailures: '{count} waiting or unavailable',
      runSkipped: '{count} skipped',
      abandonRun: 'Abandon run',
      runComplete: 'This redemption run is complete.',
      noExecutableItem: 'No item is ready right now. Retry-wait items remain in this run.',
      itemStep: 'Step {current} of {total}',
      governor: 'Governor',
      reward: 'Reward',
      rewardUnknown: 'Reward details unknown',
      prepareHandoff: 'Prepare official handoff',
      copyPlayerId: 'Copy Player ID',
      copyCode: 'Copy Gift Code',
      openOfficialCenter: 'Open official center',
      observedOutcome: 'Observed official-center outcome',
      recordContinue: 'Record and continue',
      skip: 'Skip for now',
      unavailable: 'Unavailable: {reason}',
      retryWait: 'Waiting for retry window',
      signalTitle: 'Recent redemption signal',
      signalSummary: '{successRate}% success across {samples} recent observations from {accounts} accounts.',
      signalPrivate: 'Signals appear only after privacy and sample thresholds are met.',
      copyFailed: 'Could not copy the value. Select it and copy manually.',
      outcomes: {
        redeemed: 'Redeemed',
        already_redeemed: 'Already redeemed',
        invalid: 'Invalid',
        expired: 'Expired',
        wrong_kingdom: 'Wrong Kingdom',
        rate_limited: 'Rate limited',
        temporarily_unavailable: 'Temporarily unavailable',
        permanent_failure: 'Permanent failure',
      },
      states: {
        ready: 'Ready',
        pending: 'Pending',
        awaiting_confirmation: 'Handoff prepared',
        completed: 'Completed',
        retry_wait: 'Retry wait',
        skipped: 'Skipped',
        unavailable: 'Unavailable',
      },
      rewards: {
        resource: 'Resource',
        currency: 'Currency',
        speedup: 'Speedup',
        hero_item: 'Hero item',
        chest: 'Chest',
        other: 'Other',
      },
    },
    allianceCoverage: {
      eyebrow: 'Alliance coverage',
      title: 'Gift Code Coverage',
      subtitle: 'Aggregate redemption coverage for authorized Alliance operations. Individual member history is not exposed.',
      eligibleGovernors: 'Eligible Governors',
      code: 'Gift Code',
      completed: 'Completed',
      incomplete: 'Incomplete',
      retryReady: 'Retry ready',
      unknown: 'Missing Player ID',
      expiry: 'Expiry',
      noExpiry: 'No qualified expiry',
      empty: 'No currently valid Gift Codes are available for aggregate coverage.',
      backToWorkspace: 'Back to workspace',
    },
  },
  notifications: {
    types: {
      giftCodeReminder: 'Gift Code reminder',
      giftCodeRedemptionReady: 'Gift Codes ready to redeem',
    },
  },
  receipts: {
    'gift-code-session-created': 'Gift Code redemption run created with {count} items.',
    'gift-code-personal-state-updated': 'Personal Gift Code state updated.',
    'gift-code-session-item-prepared': 'Official Gift Code handoff prepared.',
    'gift-code-session-item-recorded': 'Gift Code outcome recorded and run progress updated.',
    'gift-code-session-item-skipped': 'Gift Code item skipped for this run.',
    'gift-code-session-abandoned': 'Gift Code redemption run abandoned.',
  },
};

export function giftCodeWorkspaceLabels(): MessageCatalogue {
  return english;
}
