import type { MessageCatalogue } from './types';

const english: MessageCatalogue = {
  giftCodes: {
    workspace: {
      eyebrow: 'Redemption workspace',
      title: 'Gift Code Workspace',
      subtitle: 'Work through every currently eligible Gift Code across your owned Governors.',
      openWorkspace: 'Open redemption workspace',
      backToCatalogue: 'Back to catalogue',
      views: {
        new: 'New',
        ready: 'Ready to redeem',
        expiring: 'Expiring soon',
        retry_ready: 'Retry ready',
        in_progress: 'In progress',
        snoozed: 'Snoozed',
        completed: 'Completed',
      },
      shownCodes: '{count} codes shown',
      sourceCount: '{count} source records',
      expires: 'Expires {date}',
      noExpiry: 'No qualified expiry',
      noCodes: 'No Gift Codes match this workspace view.',
      selectCode: 'Select {code}',
      selectGovernor: 'Select {governor}',
      personalActions: 'Personal actions',
      pin: 'Pin',
      restore: 'Restore',
      snoozeDay: 'Snooze 24 hours',
      dismiss: 'Dismiss',
      remindDay: 'Remind me in 24 hours',
      createRun: 'Start redemption run',
      runModes: {
        all_actionable: 'Redeem all ready',
        expiring: 'Redeem expiring',
        retry_ready: 'Retry due items',
        selected: 'Redeem selected',
      },
      selectedSummary: '{codes} codes · {governors} Governors selected',
      currentRun: 'Current redemption run',
      runProgress: '{completed} of {total} completed',
      runFailures: '{count} waiting or unavailable',
      runSkipped: '{count} skipped',
      abandonRun: 'Abandon run',
      runComplete: 'This redemption run is complete.',
      noExecutableItem: 'No item is ready right now. Retry-wait items remain in this run.',
      itemStep: 'Step {current} of {total}',
      governor: 'Governor',
      reward: 'Reward',
      rewardUnknown: 'Reward details unknown',
      prepareHandoff: 'Prepare official handoff',
      copyPlayerId: 'Copy Player ID',
      copyCode: 'Copy Gift Code',
      openOfficialCenter: 'Open official center',
      observedOutcome: 'Observed official-center outcome',
      recordContinue: 'Record and continue',
      skip: 'Skip for now',
      unavailable: 'Unavailable: {reason}',
      retryWait: 'Waiting for retry window',
      signalTitle: 'Recent redemption signal',
      signalSummary:
        '{successRate}% success across {samples} recent observations from {accounts} accounts.',
      signalPrivate: 'Signals appear only after privacy and sample thresholds are met.',
      copyFailed: 'Could not copy the value. Select it and copy manually.',
      outcomes: {
        redeemed: 'Redeemed',
        already_redeemed: 'Already redeemed',
        invalid: 'Invalid',
        expired: 'Expired',
        wrong_kingdom: 'Wrong Kingdom',
        rate_limited: 'Rate limited',
        temporarily_unavailable: 'Temporarily unavailable',
        permanent_failure: 'Permanent failure',
      },
      states: {
        ready: 'Ready',
        pending: 'Pending',
        awaiting_confirmation: 'Handoff prepared',
        completed: 'Completed',
        retry_wait: 'Retry wait',
        skipped: 'Skipped',
        unavailable: 'Unavailable',
      },
      rewards: {
        resource: 'Resource',
        currency: 'Currency',
        speedup: 'Speedup',
        hero_item: 'Hero item',
        chest: 'Chest',
        other: 'Other',
      },
    },
    allianceCoverage: {
      eyebrow: 'Alliance coverage',
      title: 'Gift Code Coverage',
      subtitle:
        'Aggregate redemption coverage for authorized Alliance operations. Individual member history is not exposed.',
      eligibleGovernors: 'Eligible Governors',
      code: 'Gift Code',
      completed: 'Completed',
      incomplete: 'Incomplete',
      retryReady: 'Retry ready',
      unknown: 'Missing Player ID',
      expiry: 'Expiry',
      noExpiry: 'No qualified expiry',
      empty: 'No currently valid Gift Codes are available for aggregate coverage.',
      backToWorkspace: 'Back to workspace',
    },
    acquisitionOperations: {
      pageTitle: 'Gift Code acquisition operations',
      eyebrow: 'Gift Code acquisition',
      title: 'Acquisition intelligence and operations',
      help:
        'Measure source usefulness, verify transports without ingesting observations, and activate acquisition separately from source authority.',
      sourcePolicies: 'Source policies',
      evidenceEntry: 'Evidence entry',
      effectiveness: 'Acquisition effectiveness',
      effectivenessHelp:
        'These metrics are rebuildable from append-only provenance. They guide operations and never grant trust or source authority.',
      rebuild: 'Rebuild acquisition intelligence',
      codesMeasured: 'Codes measured',
      observations: 'Observations',
      medianTimeToCode: 'Median Time-to-Code',
      p95TimeToCode: 'P95 Time-to-Code',
      sourceSummary:
        '{distinct} distinct source observations · {independent} independent · {official} official · {samples} Time-to-Code samples',
      seconds: '{count} s',
      unknown: 'Unknown',
      sources: 'Source operations',
      sourcesHelp:
        'A passing smoke check is required before first activation. Push discovery, reconciliation and authority remain explicit independent controls.',
      smoke: 'Latest smoke check',
      neverChecked: 'Not checked yet',
      transportHealth: 'Transport health',
      requests: 'requests',
      gaps: 'reconciliation gaps',
      signatureFailures: 'signature failures',
      replays: 'replay rejections',
      performance: 'Derived source performance',
      uniqueCodes: 'unique codes',
      firstDiscoveries: 'first discoveries',
      useful: 'useful',
      quarantined: 'quarantined',
      runSmoke: 'Run non-ingesting smoke check',
      runHead: 'Run head acquisition',
      reconcile: 'Reconcile now',
      backfill: 'Run backfill',
      enableAcquisition: 'Enable acquisition',
      disableAcquisition: 'Disable acquisition',
      enableAuthority: 'Enable authority promotion',
      disableAuthority: 'Disable authority promotion',
      noSources: 'No registered Gift Code sources are available.',
      evidencePageTitle: 'Gift Code source evidence',
      evidenceTitle: 'Registered-source evidence entry',
      evidenceHelp:
        'Record curator-confirmed availability, invalidity, expiry, reward or applicability evidence from a registered source without inventing unsupported game facts.',
      backOperations: 'Back to acquisition operations',
      recordEvidence: 'Record source evidence',
      evidenceBoundary:
        'The exact publication URL must remain on the registered source domain. Reward and applicability facts stay unqualified until the normal evidence gate accepts them.',
      registeredSource: 'Registered source',
      selectSource: 'Select source',
      code: 'Gift Code',
      assertion: 'Assertion',
      available: 'Available',
      invalid: 'Invalid',
      expires: 'Expires',
      reward: 'Reward',
      applicability: 'Applicability',
      sourceUrl: 'Exact evidence URL',
      publishedAt: 'Published at',
      expiresAt: 'Expires at',
      expiryPrecision: 'Expiry precision',
      precisionInstant: 'Instant',
      precisionMinute: 'Minute',
      precisionHour: 'Hour',
      precisionDay: 'Day',
      precisionApproximate: 'Approximate',
      expiryTimezone: 'Expiry timezone',
      rewardName: 'Reward item name',
      rewardQuantity: 'Reward quantity',
      kingdoms: 'Applicable Kingdom numbers',
      kingdomsPlaceholder: '1501, 1502',
      kingdomsHelp: 'Enter only Kingdom numbers explicitly supported by the reviewed publication.',
      submitEvidence: 'Record verified source evidence',
      noManualSources: 'No active registered source currently permits curator-confirmed manual evidence.',
    },
  },
  notifications: {
    types: {
      giftCodeReminder: 'Gift Code reminder',
      giftCodeRedemptionReady: 'Gift Codes ready to redeem',
    },
  },
  receipts: {
    'gift-code-session-created': 'Gift Code redemption run created with {count} items.',
    'gift-code-personal-state-updated': 'Personal Gift Code state updated.',
    'gift-code-session-item-prepared': 'Official Gift Code handoff prepared.',
    'gift-code-session-item-recorded': 'Gift Code outcome recorded and run progress updated.',
    'gift-code-session-item-skipped': 'Gift Code item skipped for this run.',
    'gift-code-session-abandoned': 'Gift Code redemption run abandoned.',
    'gift-code-source-backfill-run': 'Gift Code source backfill completed.',
    'gift-code-source-push-subscribed': 'Gift Code source push subscription enabled.',
    'gift-code-source-push-unsubscribed': 'Gift Code source push subscription disabled.',
    'gift-code-source-reconciled': 'Gift Code source reconciliation completed.',
    'gift-code-source-smoke-checked': 'Gift Code source readiness smoke check completed.',
    'gift-code-source-controls-updated': 'Gift Code source acquisition controls updated.',
    'gift-code-source-head-run': 'Gift Code source head acquisition completed.',
    'gift-code-acquisition-intelligence-rebuilt': 'Gift Code acquisition intelligence rebuilt.',
  },
};

export function giftCodeWorkspaceLabels(): MessageCatalogue {
  return english;
}
