import type { MessageCatalogue } from './types';

const english: MessageCatalogue = {
  territory: {
    reconciliationTitle: 'Plan vs observed',
    reconciliationSubtitle:
      'Compare an immutable published hive plan with what was actually observed in game. Observations never overwrite the plan.',
    publishedRevisionLabel: 'Published plan revision',
    observedSnapshotLabel: 'Observed snapshot',
    chooseAllianceObservation: 'Alliance to reconcile',
    latestObservation: 'Latest authorized observation',
    noPublishedRevision:
      'Publish a Territory revision before comparing planned and observed positions.',
    noObservation:
      'No accepted spatial observation is available for this Alliance and Kingdom yet.',
    allianceRequired: 'Choose an Alliance layer before loading observed reality.',
    datasetIncompatible:
      'The plan and observation use incompatible map coordinate systems, so distance and coverage comparisons are unavailable.',
    freshnessFresh: 'Fresh observation',
    freshnessAging: 'Observation is aging',
    freshnessStale: 'Stale observation',
    observedAt: 'Observed {date}',
    observationAge: '{minutes} minutes old',
    planLayer: 'Plan',
    observedLayer: 'Observed',
    compareLayer: 'Compare',
    inPosition: 'In position',
    outOfPosition: 'Out of position',
    missing: 'Missing',
    notObserved: 'Not observed',
    unexpected: 'Unexpected',
    structuresChanged: 'Structures changed',
    lostCoverage: 'Lost coverage',
    statusInPosition: 'In position',
    statusOutOfPosition: 'Out of position',
    statusMissing: 'Missing from complete observation',
    statusNotObserved: 'Not observed — absence not proven',
    statusUnexpected: 'Unexpected observed object',
    statusAmbiguous: 'Ambiguous structure match',
    statusIdentityAmbiguous: 'Identity ambiguous',
    statusIdentityUnresolved: 'Identity unresolved',
    statusUnchanged: 'Unchanged',
    statusMoved: 'Moved',
    plannedCoordinate: 'Planned coordinate',
    observedCoordinate: 'Observed coordinate',
    delta: 'Distance delta',
    coverageDelta: 'Coverage',
    plannedCovered: 'Planned covered',
    observedCovered: 'Observed covered',
    lostCoverageLabel: 'Lost coverage',
    gainedCoverageLabel: 'Gained coverage',
    filterAll: 'All differences',
    filterOutOfPosition: 'Out of position',
    filterMissing: 'Missing',
    filterNotObserved: 'Not observed',
    filterUnexpected: 'Unexpected / unresolved',
    filterCoverage: 'Coverage changed',
    filterStructures: 'Structures changed',
    filterUncertain: 'Stale / uncertain',
    discrepancyList: 'Reconciliation details',
    observedMapOverlay: 'Published plan and observed-position overlay',
    plannedMarker: 'Planned position',
    observedMarker: 'Observed position',
    addObservedEvidence: 'Add observed map evidence',
    evidenceHelp:
      'Upload a supported map screenshot, verify every extracted coordinate, explicitly state what the screenshot covers, then commit the reviewed observation.',
    screenshotFile: 'Map screenshot',
    uploadAndClassify: 'Upload and classify',
    evidenceStatus: 'Evidence status',
    detectedKind: 'Detected screenshot class',
    extractedCandidates: 'Extracted coordinate candidates',
    viewScreenshot: 'View retained screenshot',
    reviewObservation: 'Review observed spatial facts',
    capturedAt: 'Observed at',
    coverageKind: 'Observation coverage',
    completeness: 'Completeness',
    coverageCompleteHive: 'Complete hive',
    coverageCompleteVisibleRegion: 'Complete visible region',
    coveragePartialRegion: 'Partial region',
    coverageSingleObject: 'Single object',
    coverageUnknown: 'Unknown coverage',
    completenessComplete: 'Complete',
    completenessPartial: 'Partial',
    completenessUnknown: 'Unknown',
    coverageBounds: 'Visible-region bounds',
    coordinateX: 'X',
    coordinateY: 'Y',
    width: 'Width',
    height: 'Height',
    identity: 'Governor identity',
    unresolvedIdentity: 'Unresolved',
    ambiguousIdentity: 'Ambiguous',
    reviewAndApprove: 'Save reviewed observation',
    semanticDuplicate: 'Equivalent reviewed observation already exists',
    duplicateJustification: 'Why should this duplicate be accepted?',
    resolveDuplicate: 'Resolve duplicate',
    commitObservation: 'Commit observed facts',
    committedObservation: 'Committed to spatial observation history',
    retryProcessing: 'Retry processing',
    deleteEvidence: 'Delete retained evidence',
    invalidateObservation: 'Invalidate observation',
    invalidationReason: 'Why is this observation invalid?',
    noEvidence: 'No Territory map evidence has been uploaded in this current Alliance scope.',
    observationProvenance: 'Observation provenance',
    evidenceReceipt: 'Destination receipt',
    exactPlanRemains: 'Published plan remains unchanged',
    compareBackToEditor: 'Back to Hive Builder',
    identityResolvedPlayer: 'Matched application Governor',
    identityResolvedPlanLocal: 'Matched plan-local Governor',
  },
};

export function territoryReconciliationLabels(): MessageCatalogue {
  return english;
}
