import type { MessageCatalogue } from './types';

const english: MessageCatalogue = {
  kingdomP7D: {
    transferEvidenceTitle: 'In-game evidence',
    transferEvidenceHelp:
      'Add a supported KingShot Transfer screenshot, verify what the game actually shows, review every extracted fact, preview the eligibility impact, then commit explicitly.',
    addInGameEvidence: 'Add in-game evidence',
    screenshotClass: 'Screenshot class',
    uploadScreenshot: 'Screenshot file',
    uploadEvidence: 'Upload and classify',
    evidenceLoading: 'Loading Transfer Evidence…',
    evidenceLoadFailed: 'Transfer Evidence could not be loaded.',
    noTransferEvidence: 'No in-game Transfer Evidence has been added for this Governor.',
    expectedClass: 'Expected class',
    detectedClass: 'Detected class',
    classificationConfidence: 'Classification confidence',
    classificationReason: 'Classifier result',
    fieldConfidence: 'Field confidence',
    evidenceField: 'Field',
    evidenceCorrected: 'corrected',
    belowSchemaConfidence: 'Below the schema confidence requirement — verify carefully.',
    rawObservation: 'Raw observation',
    normalizedValue: 'Normalized candidate',
    schemaVersion: 'Schema version',
    fixtureCorpus: 'Fixture corpus',
    destinationAction: 'Destination action',
    reviewEvidence: 'Review / correct evidence',
    reviewBeforeCommit: 'Human review is required before any Transfer fact can be committed.',
    uploadTime: 'Uploaded at',
    observationTime: 'Observation time',
    freshnessBoundary: 'Valid until',
    freshnessRequiredHelp:
      'Choose the validity boundary that applies to this mutable game observation. Evidence does not invent a global freshness TTL.',
    currentTransferFacts: 'Current Transfer facts',
    currentEligibility: 'Current eligibility',
    reviewedFacts: 'Reviewed screenshot facts',
    correctionsHelp:
      'Changing a value here records a new reviewed revision. The original OCR text and machine confidence remain unchanged.',
    targetKingdomNumber: 'Target Kingdom number',
    passesAvailable: 'Transfer Passes available',
    passesRequired: 'Transfer Passes required',
    invitationStatus: 'Invitation status',
    officialGroupIdentifier: 'Official Transfer Group',
    officialGroupKingdoms: 'Visible Kingdom membership',
    previewImpact: 'Preview destination facts and eligibility impact',
    beforeImport: 'Before commit',
    afterImport: 'After reviewed facts',
    remainingAction: 'Highest-priority remaining action',
    reviewedFactKeys: 'Facts this screenshot would add',
    semanticDuplicate: 'Semantic duplicate detected',
    semanticDuplicateHelp:
      'Equivalent reviewed game state already exists in this Transfer scope. Resolve the duplicate explicitly before commit.',
    duplicateJustification: 'Why should this duplicate be accepted?',
    resolveDuplicate: 'Resolve duplicate',
    visualDuplicate: 'Possible visual duplicate',
    visualDuplicateHelp:
      'The image resembles earlier evidence. Review it normally; visual similarity is not destination idempotency.',
    commitEvidence: 'Commit reviewed facts',
    committedEvidence: 'Committed to Kingdom Transfer history',
    retryProcessing: 'Retry processing',
    deleteEvidence: 'Delete retained evidence',
    deleteEvidenceConfirm:
      'Delete the retained screenshot and Evidence-owned raw material? Accepted Kingdom Transfer facts will remain.',
    processingStatus: 'Evidence status',
    evidenceImage: 'View retained screenshot',
    unsupportedEvidence: 'Unsupported or ambiguous screenshot',
    classMismatch: 'The detected screenshot class does not match the class selected at upload.',
    previewRequired: 'Preview the destination impact before committing this review.',
    reviewApproved: 'Human review approved',
    destinationReceipt: 'Destination receipt',
    evidenceWarnings: 'Warnings',
    evidenceNoWarnings: 'No extraction warnings',
    evidenceRevision: 'Review revision',
    evidenceDeleted: 'Evidence source deleted',
    evidenceKind_unknown: 'Unknown / unsupported',
    evidenceKind_transfer_governor_status: 'Transfer Governor status',
    evidenceKind_transfer_score_passes: 'Transfer Score / Passes',
    evidenceKind_transfer_invitation: 'Transfer invitation',
    evidenceKind_transfer_target_kingdom_rules: 'Target Kingdom transfer rules',
    evidenceKind_transfer_official_group: 'Official Transfer Group',
    evidenceStatus_uploaded: 'Uploaded',
    evidenceStatus_classifying: 'Classifying',
    evidenceStatus_classified: 'Classified',
    evidenceStatus_extracting: 'Extracting',
    evidenceStatus_needs_review: 'Needs review',
    evidenceStatus_approved: 'Approved',
    evidenceStatus_committing: 'Committing',
    evidenceStatus_committed: 'Committed',
    evidenceStatus_unsupported: 'Unsupported',
    evidenceStatus_failed: 'Failed',
    evidenceStatus_deleted: 'Deleted',
    evidenceReviewStatus_approved: 'Approved',
    evidenceReviewStatus_duplicate_blocked: 'Duplicate blocked',
    evidenceCommitStatus_pending: 'Pending',
    evidenceCommitStatus_succeeded: 'Succeeded',
    evidenceCommitStatus_failed: 'Failed',
  },
};

export function transferEvidenceLabels(): MessageCatalogue {
  return english;
}
